### PR TITLE
Update Gecko driver version to 0.26.0

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by tomasdavidorg** [comment]
Build is green. Ready to be merged.

**Pull request merged**
