### PR TITLE
BXMSPROD-963 pull_request.yml updated

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-963

[strategy.fail-fast](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) to **false** since java 11 is working
depends on:
- https://github.com/kiegroup/lienzo-core/pull/124
- https://github.com/kiegroup/lienzo-tests/pull/105
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1447
- https://github.com/kiegroup/kie-soup/pull/154
- https://github.com/kiegroup/appformer/pull/1037
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/459
- https://github.com/kiegroup/drools/pull/3063
- https://github.com/kiegroup/optaplanner/pull/901
- https://github.com/kiegroup/jbpm/pull/1739
- https://github.com/kiegroup/kie-jpmml-integration/pull/39
- https://github.com/kiegroup/droolsjbpm-integration/pull/2210
- https://github.com/kiegroup/openshift-drools-hacep/pull/97
- https://github.com/kiegroup/droolsjbpm-tools/pull/116
- https://github.com/kiegroup/kie-uberfire-extensions/pull/103
- https://github.com/kiegroup/kie-wb-playground/pull/94
- https://github.com/kiegroup/kie-wb-common/pull/3401
- https://github.com/kiegroup/drools-wb/pull/1414
- https://github.com/kiegroup/optaplanner-wb/pull/378
- https://github.com/kiegroup/jbpm-designer/pull/888
- https://github.com/kiegroup/jbpm-work-items/pull/142
- https://github.com/kiegroup/jbpm-wb/pull/1457
- https://github.com/kiegroup/kie-docs/pull/2787
- https://github.com/kiegroup/optaweb-employee-rostering/pull/492
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/353
- https://github.com/kiegroup/kie-wb-distributions/pull/1053

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://www.example.com)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</pre>

### CODE REVIEW

**Comment by Ginxo** [comment]
Need Investigation
```
2020-08-27T15:20:42.5235572Z [ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (generate-single-html) on project jbpm-docs: Execution generate-single-html of goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc failed. ArrayIndexOutOfBoundsException -> [Help 1]
2020-08-27T15:20:42.5240894Z org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (generate-single-html) on project jbpm-docs: Execution generate-single-html of goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc failed.
2020-08-27T15:20:42.5244685Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
2020-08-27T15:20:42.5245517Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2020-08-27T15:20:42.5246563Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
2020-08-27T15:20:42.5248513Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2020-08-27T15:20:42.5250662Z     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
2020-08-27T15:20:42.5252715Z     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
2020-08-27T15:20:42.5253771Z     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
2020-08-27T15:20:42.5255319Z     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
2020-08-27T15:20:42.5256205Z     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
2020-08-27T15:20:42.5257639Z     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
2020-08-27T15:20:42.5259093Z     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
2020-08-27T15:20:42.5260083Z     at java.lang.Thread.run (Thread.java:748)
2020-08-27T15:20:42.5263731Z Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate-single-html of goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc failed.
2020-08-27T15:20:42.5265111Z     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
2020-08-27T15:20:42.5265792Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
2020-08-27T15:20:42.5267306Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
2020-08-27T15:20:42.5268181Z     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
2020-08-27T15:20:42.5269654Z     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
2020-08-27T15:20:42.5271185Z     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)
2020-08-27T15:20:42.5272690Z     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)
2020-08-27T15:20:42.5273877Z     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
2020-08-27T15:20:42.5274935Z     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:511)
2020-08-27T15:20:42.5276139Z     at java.util.concurrent.FutureTask.run (FutureTask.java:266)
2020-08-27T15:20:42.5323806Z     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
2020-08-27T15:20:42.5324642Z     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
2020-08-27T15:20:42.5324898Z     at java.lang.Thread.run (Thread.java:748)
2020-08-27T15:20:42.5325096Z Caused by: java.lang.ArrayIndexOutOfBoundsException
```

**Comment by mareknovotny** [comment]
the error in https://github.com/kiegroup/kie-wb-distributions/pull/1053#issuecomment-682343417 is from concurrent acces in parallel build. I am not sure if that can be turn off just for kie-docs repository?

**Comment by mareknovotny** [comment]
we can run debug on GA, right?
we should also report this as issue in https://github.com/asciidoctor/asciidoctor-maven-plugin/issues, they claim the plugin is threadsafe, but there could be a bug in used some method from jdk to not be synchronized

**Comment by Ginxo** [comment]
we have also a random problem @mareknovotny can we disable `gwt` here? https://github.com/kiegroup/kie-wb-distributions/pull/1053/checks?check_run_id=1040303155
```
2020-08-28T07:49:57.9054460Z [INFO]    Computing all possible rebind results for 'org.jboss.errai.ioc.client.Type_factory__o_j_w_p_c_e_d_l_ProcessDefinitionListViewImpl__quals__j_e_i_A2020-08-28T07:50:00.6537738Z ##[error]No space left on device
```

**Comment by Ginxo** [comment]
parallel build removed from https://github.com/kiegroup/kie-docs/pull/2787, relaunching

**Pull request merged**
