### PR TITLE
[RHPAM-4564] update EAP XP to version 4.0.0.GA-redhat-00009

### PR DESCRIPTION
**Pull request by rgdoliveira**
This prod version is the latest released version and it is EAP XP on top of EAP 7.4.7

**Jira** https://issues.redhat.com/browse/RHPAM-4564

**referenced Pull Requests**: 
- https://github.com/kiegroup/kie-wb-distributions/pull/1199
- https://github.com/kiegroup/kie-wb-distributions/pull/1200
- https://github.com/kiegroup/kie-wb-distributions/pull/1201

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by rgdoliveira** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
Do we have jira for this upgrade?

**Comment by mareknovotny** [comment]
FDB is not needed ;)

**Comment by rgdoliveira** [comment]
> Do we have jira for this upgrade?

We don't, should I create  a Jira for it?

**Review by tomasdavidorg — APPROVED** [review]
I built this locally and did some quick checks and looks good to me. I will check results of the tests on nightlies after this is merged.

**Comment by rgdoliveira** [comment]
Jenkins run fdb

**Review by lampajr — APPROVED** [review]

**Comment by rgdoliveira** [comment]
I've rerun the `Linux - Pull Request` job and it succeeded, see run [#207](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-wb-distributions-main.pr/207/)

**Pull request merged**
