### PR TITLE
RHDM-252 Updated branding for RHDM.

### PR DESCRIPTION
**Pull request by AntStephenson**
Updated RHDM branding changes.

### CODE REVIEW

**Comment by AntStephenson** [comment]
jenkins retest this

**Comment by AntStephenson** [comment]
@cristianonicolai  I don't know if we can just merge this regardless of the failed build, it seems there's a bug in the plugin.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
@mbiarnes could you take a look on Jenkins? builds a consistently failing in this repo.

**Comment by cristianonicolai** [comment]
@AntStephenson no idea why your PR keeps failing as others pass. Perhaps give it a go to rebase it and open a new one?

**Comment by AntStephenson** [comment]
I spoke to Petr and it's basically a difficult to reproduce bug with the
GitHub API returning some null data. The fix is to update the plugin to
retry the lookup and include a workaround to clear the cached API response
(it's why retriggering keeps failing).

I'll go with your suggestion in the mean time!

**Pull request closed without merging**
