### PR TITLE
AF-930: [Layout Editor] Use dock panels to increase the editor content area

### PR DESCRIPTION
**Pull request by dgutierr**
Changes required by kiegroup/appformer#125

Do not merge yet.

### CODE REVIEW

**Comment by kkufova** [comment]
jenkins please retest this

**Comment by jhrcek** [comment]
@dgutierr I built the 4 PRs locally and I reproduced 2 failures in selenium tests both by running 
1. `mvn clean install -Pwildfly10,kie-wb -Dwebdriver.firefox.bin=PATH_TO_FIREFOX_BINARY_VERSION_46_OR_LESS -Dit.test=StandalonePerspectivesIntegrationTest` in directory `kie-wb-distributions/kie-wb-tests/kie-wb-tests-gui` and then also
2. manually as well, using the following steps to reproduce  (just emulating what selenium does, after I deployed the kie-wb.war to eap7.1)
 
Steps to reproduce:
1. login to business-central using login dialog as usual
2. after home is loaded, enter this url into browser adress bar and press enter http://localhost:8080/kie-wb/kie-wb.jsp?standalone=true&perspective=AuthoringPerspective&header=AppNavBar

Expected result: standalone authoring is loaded
Actual result: only top navbar is loaded, but perspective content remains empty (the same as [screenshot in tests](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-distributions-pullrequests/893/artifact/kie-wb-tests/kie-wb-tests-gui/target/screenshots/StandalonePerspectivesIntegrationTest_testAuthoringPerspectiveWithHeader.png)

 It seems that this PR ensemble somehow breaks the authoring.Unfortunately I failed to identify which change in this PR breaks that :-( Maybe @manstis could help identify the root cause of this strange behavior?

**Comment by jhrcek** [comment]
Other perspectives are working fine in standalone mode, e.g.:
http://localhost:8080/business-central/kie-wb.jsp?standalone=true&perspective=LibraryPerspective

**Comment by dgutierr** [comment]
@jhrcek No idea what those are failing tbh. I do not see any relationship between the changes done and the failures. Can you look into it a little bit more please?

**Comment by jhrcek** [comment]
Ok, I'll check tomorrow. In the meantime Jenkins execute full downstream build . I suppose this PR is rebased onto latest master - if not @dgutierr could you please rebase it again and rerun full build again?

**Comment by jhrcek** [comment]
@dgutierr I played with the war built in [pr job](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-distributions-pullrequests/914/). I encountered many weird issues (JS errors when creating new pages, "Place already closed" when closing page editor etc.) Since I must work on other tasks I agreed with @kkufova that should would play with it and provide more details about those errors.

> I do not see any relationship between the changes done and the failures. 

I suspect it might have something to do with [these changes](https://github.com/kiegroup/kie-wb-common/pull/1335/files#diff-2deba6796b3695c6eac597ed0fbd65d3R42) in AuthoringWorkbenchDocks. You must have done some change that causes the AuthoringPerspective to no longer load in standalone mode. I just tried with latest 7.6.0 snapshot and there it sill works fine. Maybe look [here](https://github.com/kiegroup/appformer/blob/master/uberfire-workbench/uberfire-workbench-client/src/main/java/org/uberfire/client/workbench/Workbench.java#L260-L278) for more details about how standalone mode works.

**Comment by jhrcek** [comment]
FYI this is what I see after pasting the following url to browser on master where it works fine

http://localhost:8080/kie-wb/kie-wb.jsp?standalone=true&perspective=AuthoringPerspective&header=AppNavBar

standaloneauthoring


With your changes Project Explorer is no longer loaded, which causes those selenium tests to fail, because it [doesn't see project explorer panel](https://github.com/kiegroup/kie-wb-distributions/blob/master/kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/StandalonePerspectivesIntegrationTest.java#L70-L76) when using that URL

**Comment by dgutierr** [comment]
jenkins execute full downstream build

**Comment by dgutierr** [comment]
@jhrcek @kkufova Did a full testing of the CMS perspective, the form editor and the authoring standalone mode. After a few adjustments, everything seems to be ok now.

Please have a look.

**Comment by kkufova** [comment]
I tried it manually and the standalone perspectives work well now, thanks!

**Pull request merged**
