### PR TITLE
JBPM-7034: deleting Pages perspective -> unable to return it back

### PR DESCRIPTION
**Pull request by dgutierr**
@kkufova  Can you review please?

### CODE REVIEW

**Comment by kkufova** [comment]
Just a note: was the issue valid though? The Home page contains the link to the Pages perspective as well, so in my opinion, it is always possible to go back there, even if the item is no longer available in the Mega menu. WDYT?

**Comment by dgutierr** [comment]
@kkufova  IMO is always better to enforce the Pages entry is something which must be always present.

**Comment by dgutierr** [comment]
@manstis  Can you have a look please?

**Comment by kkufova** [comment]
The `org.kie.wb.test.rest.functional.JobIntegrationTest.org.kie.wb.test.rest.functional.JobIntegrationTest` is definitely a random failure, but I'm not sure about the `org.kie.wb.test.rest.functional.ProjectIntegrationTest.testDeployProjectTwice` test.

jenkins please retest this

**Comment by dgutierr** [comment]
jenkins execute full downstream build

**Comment by kkufova** [comment]
jenkins execute full downstream build

**Comment by dgutierr** [comment]
@manstis Can you please merge this and the 7.7.x related one?

**Comment by manstis** [comment]
@dgutierr It'll be my pleasure.. was you planning on getting a green build first?

**Comment by dgutierr** [comment]
@manstis I think so, despite there are some unrelated test failures, not related to this PR. @kkufova wdyt?

**Comment by kkufova** [comment]
jenkins please retest this

**Comment by kkufova** [comment]
@dgutierr, @manstis, I rebased on `master` and tried to build the PR locally. The build fails with

`/kie-wb-common/kie-wb-common-widgets/kie-wb-metadata-widget/src/main/java/org/kie/workbench/common/widgets/metadata/client/KieEditor.java:[305,30] method onValidate in class org.uberfire.ext.editor.commons.client.BaseEditor<T,M> cannot be applied to given types;
[ERROR] required: org.uberfire.mvp.Command
[ERROR] found: no arguments`

The error is not related to this PR, it is caused by https://github.com/kiegroup/appformer/pull/259. When I was doing the initial preview, the build passed locally, so I would merge this with a clear conscience. :-)

**Comment by manstis** [comment]
@dgutierr @kkufova The referenced PR was one of an ensemble - and the others were not merged. This has been rectified and this PR should now build OK... Therefore...

Jenkins please retest this.

**Comment by kkufova** [comment]
@manstis The build passed. :-)

**Pull request merged**
