### PR TITLE
[7.59.x] AF-2880 : Support Elytron in Business Central 

### PR DESCRIPTION
**Pull request by Rikkola**
**JIRA**: 

[AF-2880](https://issues.redhat.com/browse/AF-2880)

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1776
* https://github.com/kiegroup/kie-soup/pull/231
* https://github.com/kiegroup/appformer/pull/1199
* https://github.com/kiegroup/droolsjbpm-integration/pull/2611
* https://github.com/kiegroup/jbpm-wb/pull/1518
* https://github.com/kiegroup/kie-wb-distributions/pull/1132

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
I can't see here https://github.com/Rikkola/kie-wb-distributions/pull/3/files. Have you missed that?

**Comment by mareknovotny** [comment]
Also there are conflicts so please rebase your branch

**Review by mareknovotny — CHANGES_REQUESTED** [review]
There is needed also `<installArtifactClassifier>standalone</installArtifactClassifier>` in wildfly-jar-maven-plugin configuration

**Comment by Rikkola** [comment]
installArtifactClassifier added and rebase was not needed. I was targeting main not 7.59.x

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
even the Jenkins CI shows as red, it was timed out but only in the final stage so all ran as green.

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by Rikkola** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
@Ginxo any idea why GHA didn't launch here?

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by Ginxo** [comment]
@mareknovotny it seems to be due to the base branch changing performed by @Rikkola 10 days ago (and no other commit has been pushed)
image

It seems (and again it seems, because this is the only reason I find) the check_runs have been lost due to that.
You can check the [checks tab](https://github.com/kiegroup/kie-wb-distributions/pull/1132/checks?check_run_id=3752471679) -> check's history section and you will notice the job has been triggered for every commit pushed here
image

I've commit [something silly](https://github.com/kiegroup/kie-wb-distributions/pull/1132/commits/c9984479458b443b7bf972ea6a72016b09c2543e) and the checks are back again.

**Comment by Ginxo** [comment]
I've posted an issue for this https://github.community/t/the-check-runs-are-lost-after-changing-prs-base-branch/203804

**Pull request merged**
