### PR TITLE
RHPAM-2529: org.jboss.errai:errai-bus dependency removed from business-central-webapp project

### PR DESCRIPTION
**Pull request by Ginxo**
RHPAM-2529

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mareknovotny** [comment]
Jenkins please retest this

**Comment by mareknovotny** [comment]
Jenkins please retest this

**Comment by mareknovotny** [comment]
so backport is green #996

**Comment by Ginxo** [comment]
Jenkins please retest this

**Pull request merged**
