### PR TITLE
BXMSPROD-784 assembly-kie-wb-eap-7-redhat.xml wildfly-14 error fixed

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-784
fixes https://github.com/kiegroup/kie-wb-distributions/pull/1022

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins execute full downstream production build

**Comment by AntStephenson** [comment]
LGTM

**Comment by Ginxo** [comment]
@mareknovotny @winklerm @AntStephenson @almope 
One test failure `org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT` which is related with kie-wb-distributions itself. Is it due to the change?
```
3:57:15,519 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "business-monitoring-webapp.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"business-monitoring-webapp.war\".WeldStartService" => "Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: No filesystem for uri (default://system/system) found.
    Caused by: org.uberfire.java.nio.file.FileSystemNotFoundException: No filesystem for uri (default://system/system) found."}}
```

**Comment by winklerm** [comment]
The `org.kie.bc.DeploymentIT` test failure seems to be present upstream as well [1], so we can probably merge this PR.

[1] https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/daily-build-prod/job/daily-build-prod-pipeline-master/185/console

**Comment by mareknovotny** [comment]
Jenkins execute full downstream production build

**Pull request merged**
