### PR TITLE
BXMSPROD-33 remove the eap descriptor reference from the notProductizedProfile (business-central and business-monitoring) and remove the file assembly-kie-wb-eap-7.xml

### PR DESCRIPTION
**Pull request by Ginxo**

### CODE REVIEW

**Comment by mareknovotny** [comment]
ok to test

**Comment by mareknovotny** [comment]
Jenkins retest this, please

**Comment by mareknovotny** [comment]
@Ginxo there is some inconsistency in referenced 'business-central-parent/business-central-distribution-wars/src/main/community/assembly-kie-wb-eap-7.xml'.

**Comment by Ginxo** [comment]
my mistake, assembly-kie-wb-eap-7.xml descriptor reference removed from notProductizedProfile profile according to @mareknovotny's indications

**Comment by mareknovotny** [comment]
Jenkins retest this, please

**Comment by Ginxo** [comment]
@mareknovotny  done

**Pull request closed without merging**
