### PR TITLE
AF-1709: Adding Profile Backend dependency

### PR DESCRIPTION
**Pull request by jesuino**
Part of an ensemble:

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/892
https://github.com/kiegroup/kie-wb-common/pull/2304
https://github.com/kiegroup/kie-wb-distributions/pull/849

### CODE REVIEW

**Comment by jhrcek** [comment]
jenkins retest this

**Comment by ederign** [comment]
jenkins retest this

**Comment by jesuino** [comment]
jenkins retest this

**Comment by jesuino** [comment]
jenkins retest this

**Comment by jesuino** [comment]
I found the problem, since version was incremented my commit in kie-wb-common was still referring to 7.15.0-SNAPSHOT

**Comment by jesuino** [comment]
jenkins retest this

**Comment by ederign** [comment]
Tests are not related.

**Pull request merged**
