### PR TITLE
Remove tomcat distribution of workbenches

### PR DESCRIPTION
**Pull request by jhrcek**
1. Red Hat is officially not supporting tomcat disto of workbenches
2. QE is not paying ANY attention to testing workbench on tomcat
3. tomcat distros of workbenches are broken and nobody has time to fix them (see 1 above)
4. We have swarm as "lightweight" distribution of the workbench(es)
which can be considered as a replacement for tomcat distro
5. In the past there were some hacks required to make workbenches work on tomcat
6. Not having to archive the 3 tomcat wars will save ~450MB per each full downstream build.

Part of ensemble:
https://github.com/kiegroup/kie-jenkins-scripts/pull/319
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/807
https://github.com/kiegroup/kie-wb-distributions/pull/800

### CODE REVIEW

**Comment by jhrcek** [comment]
2 failed selenium tests (showing loading animations) + 1 rest test seem to be cause by jenkins slave being slow. Trying again: jenkins retest this

**Comment by jhrcek** [comment]
There were no objections to my proposal of removing tomcat distribution of workbenches (sent to wide audience of bsig-all and sme-bpm). Only two "go ahead" replies sent to me off-list. The build is green. @manstis I think we're safe to merge these 2 PRs

**Comment by manstis** [comment]
@jhrcek Could you have the two "go ahead" people approve these PRs?

**Comment by jhrcek** [comment]
@porcelli @Rikkola could you review/approve this PR?

**Comment by manstis** [comment]
@jhrcek IIRC there's a Tomcat "valve" somewhere too; that was used to integrate authentication.

If I find it I'll let you know where!

**Comment by manstis** [comment]
@jhrcek https://github.com/kiegroup/droolsjbpm-integration/tree/master/kie-tomcat-integration

**Comment by jhrcek** [comment]
@manstis Thanks, will look into removing that too.

**Comment by jhrcek** [comment]
@porcelli please check this too when you're back from PTO. Best to have approval of multiple senior engineers before we merge this.

**Comment by jhrcek** [comment]
1 failure due to slow firefox startup in selenium tests.
jenkins retest this

**Comment by jhrcek** [comment]
1 failure due to project import in selenium tests taking too long. Jenkin slaves seem to be kind of slow today. 
jenkins retest this

**Comment by jhrcek** [comment]
jenkins retest this

**Comment by jhrcek** [comment]
jenkins retest this

**Comment by jhrcek** [comment]
@manstis 1 failure in LoginLogout selenium tests - due to Firefox not starting fast enough. This test passed multiple times previously with this PR. I think we should merge this and I'll look into stabilizing those selenium tests (updating selenium version and using newer firefox in our CI).

**Pull request merged**
