### PR TITLE
AF-593: Decouple kie-wb-common-datamodel from Drools

### PR DESCRIPTION
**Pull request by mbarkley**
Related:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/541
https://github.com/kiegroup/droolsjbpm-knowledge/pull/263
https://github.com/kiegroup/drools/pull/1444
https://github.com/kiegroup/jbpm/pull/973
https://github.com/kiegroup/droolsjbpm-integration/pull/1163
https://github.com/kiegroup/kie-wb-common/pull/1133
https://github.com/kiegroup/drools-wb/pull/596
https://github.com/kiegroup/jbpm-designer/pull/654
https://github.com/kiegroup/jbpm-wb/pull/864
https://github.com/kiegroup/optaplanner-wb/pull/218
https://github.com/kiegroup/droolsjbpm-tools/pull/82

### CODE REVIEW

**Comment by manstis** [comment]
That's a bolt from the blue. Why do we now need this dependency? You said this module needed a PR but I wasn't expecting this!

**Comment by mbarkley** [comment]
@manstis So there are two possible MVELEvaluators. One is the "raw" evaluator and the other is a "safe" one. The logic for determining which one to use lives in drools.

I didn't want to leave the possibility of webapps compiling accidentally with the raw evaluator if the safe one was desired so there is no CDI bean satisfying MVELEvaluator in AppFormer (the RawEvaluator does, but it's not in a bean archive so not injectable out-of-the-box).

My best guess at where to put a producer method for the MVELEvaluator was in drools-cdi, so that's why I've added this dependency. If you can suggest a better place for a producer method for the evaluator, I would happily go along with that.

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Pull request merged**
