### PR TITLE
GUVNOR-3095 : Make 6.4.x Inbox optional

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/GUVNOR-3095

https://github.com/kiegroup/guvnor/pull/454
https://github.com/kiegroup/kie-wb-distributions/pull/530

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@Rikkola approved; but I suspect there's something wrong with Jenkins configuration as it's trying to copy some non-existent files causing the job to fail. @mbiarnes would you mind taking a look?

**Comment by Rikkola** [comment]
@manstis Thanks. I think I saw the branch has some trouble passing the build even without this.

**Comment by Rikkola** [comment]
jenkins please retest this

**Comment by Rikkola** [comment]
Thanks @manstis

**Pull request merged**
