### PR TITLE
JBPM-6511: Remove the Business Dashboards entry from mega menu

### PR DESCRIPTION
**Pull request by dgutierr**
Changes done:

1.- The "Track>Business Dashboards" have been removed from all the workbench webapps.
In the case of kie-drools-wb the entire "Track" section has been removed as it just contained a single entry.

2.- The "Design>Dashboards" section has been renamed to "Design>Pages" since the tooling focuses on the creation of pages in general, not only dashboards.

@jhrcek @manstis would you mind to review please?

### CODE REVIEW

**Comment by jhrcek** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
@dgutierr If the goal of this PR was to make the "AppsPerspective" no longer accessible, than there's still one place that I can use to navigate to that perspective. There's still the link on the home page, hidden behind the arrow icon.  screenshot

Otherwise the changes are working fine in both kie-wb

**Comment by dgutierr** [comment]
@jhrcek I've fixed both. I had to push another PR https://github.com/kiegroup/kie-wb-common/pull/1298. Please take a look.

**Comment by dgutierr** [comment]
@jhrcek I missed a required change in drools-wb => https://github.com/kiegroup/drools-wb/pull/722

Jenkins execute full downstream build

**Comment by dgutierr** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
@dgutierr Just FYI: full downstream build doesn't work for kie-wb-distributions, because it's at the end of "food chain". Every normal build of this repo produces final WARs, so no need for full downstream build. After you fix the build issue in drools-wb, please execute the downstr.build there.

**Comment by dgutierr** [comment]
Jenkins execute full downstream build

**Comment by jhrcek** [comment]
@dgutierr I finally verified that apps is no longer accessible and all the issues mentioned have been fixed. + 1 to merge.

There is one issue I noticed when testing it: when you open the "list of perspectives" widget in the security management perspective and start typing in text to filter perspective names, the error modal is opened as in the following screenshot. This problem is also present in the master, so let's not block merging this PR. I'm just writing it here to ask @tomasdavidorg  here if this issue is known and reported:
screenshot from 2017-12-04 17-17-22

**Comment by jhrcek** [comment]
@dgutierr FYI I opened new jira for the above mentioned issue: [AF-919](https://issues.jboss.org/browse/AF-919). It's also present on master, so it should not block merging this PR.

**Comment by dgutierr** [comment]
@manstis This one as well please :-)

**Comment by manstis** [comment]
@dgutierr This one I'd be more cautious about (especially as I cannot see why it failed anymore). There are Selenium tests checking navigation to the different perspectives.. if one has changed (either add, remove or change in identifier) the tests could break... so this PR has the potential to break things...

For the reason.. Jenkins please execute full downstream build.

**Comment by dgutierr** [comment]
@manstis  I agree, but notice @jhrcek approved it. So it should not break anything imho.

**Comment by jhrcek** [comment]
@manstis please let me double check locally before merging..

**Comment by manstis** [comment]
@dgutierr Sure.. I assume when someone approves/tests function they've **not** necessarily ran the Selenium tests as part of their sign-off (as it'd require a ```-Dfull``` local build of the entire ```kie-wb-distributions``` repository). If I'm mistaken then someone just need tell me :-)

**Comment by jhrcek** [comment]
@manstis I was just not sure if I missed something, but David updated selenium tests appropriately, so +1 to merge. Please don't forget to merge the dependency of this PR https://github.com/kiegroup/kie-wb-common/pull/1298 before merging this.

If these changes break selenium tests, I take responsibility for that and I promise to fix them soon ;)

**Pull request merged**
