### PR TITLE
RHDM-318: Replace DevOps word by Deploy on Navigation/Menu/Mega Menu

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by ederign** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by ederign** [comment]
Jenkins is down. It's green locally and we talked with @etirelli

**Pull request merged**
