### PR TITLE
DROOLS-2243 Add kie-pmml visibility to workbench

### PR DESCRIPTION
**Pull request by lanceleverich**

### CODE REVIEW

**Comment by lanceleverich** [comment]
Latest push includes the update to kie-wb-webapp/pom.xml

**Comment by mareknovotny** [comment]
What will we do with this PR?
These 2 dependencies were addedd already in #659 into Drools-BOM. Do we need to merge this?

@lanceleverich, @etirelli , @manstis wdyt?

**Comment by manstis** [comment]
@mareknovotny The PR you link references ```appformer-bom``` not ```drools-bom``` however I see the PMML modules are included in the ```drools-bom``` imported into ```kie-wb-distributions```. That said the ```drools-bom``` only declares them in the ```<dependencyManagement>``` section and hence I'd have thought we still need to declare them as concrete dependencies here?

Ultimately it's for @lanceleverich to advise.

**Comment by mareknovotny** [comment]
@manstis my bad, I wanted to link here https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/659

**Comment by mareknovotny** [comment]
@lanceleverich do you still want to insist on this PR? Rebase is required ;)

**Comment by lanceleverich** [comment]
No, another PR will replace it.

**Comment by mareknovotny** [comment]
ok, no objection to close this

**Pull request closed without merging**
