### PR TITLE
[7.0.x] Default translation (locale == null) should be returned when there is no translation to a key in the active locale and the errai.i18n.default_per_key is set to true.

### PR DESCRIPTION
**Pull request by paulovmr**
Depends on: https://github.com/errai/errai/pull/248

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
The build will pass only when https://github.com/errai/errai/pull/248 is merged (both 7.0.x and master points to Errai's master branch).

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by manstis** [comment]
@mbarkley @paulovmr I've not merged this into our 7.0.x branch **today** as @mbiarnes is to perform a CR2 release from our 7.0.x branch and merging this PR would necessitate an Errai release (I don't know if your time-zones/time-frames align with Michael's for release... if the moons align ping me and I'm happy to merge!)

**Comment by paulovmr** [comment]
@manstis Thanks for the warning. It would be important to have this on CR2.

@mbiarnes @mbarkley Hi, is it possible to perform an Errai release together with the CR2 release? If yes, @manstis can go ahead and merge this.

**Comment by mbarkley** [comment]
@manstis I will do an Errai release today, so you can safely merge Paulo's PR.

/cc @paulovmr @mbiarnes

**Comment by manstis** [comment]
Thanks @mbarkley 

Please let @mbiarnes know the new version to use for KIE 7.0.0.CR2.

**Pull request merged**
