### PR TITLE
[JBPM-5766] add 'process-admin' role

### PR DESCRIPTION
**Pull request by psiroky**
@dgutierr is this everything needed in order to add new role or did I miss someting?

### CODE REVIEW

**Comment by psiroky** [comment]
@dgutierr thanks! @krisv could you please take a look at those permissions and let me know if there is something missing? I am not exactly sure what the role should be capable of doing.

**Comment by psiroky** [comment]
The two failing tests are failing on master as well for past several days.

**Comment by krisv** [comment]
+1, permissions look ok

**Comment by psiroky** [comment]
jenkins retest this

**Pull request merged**
