### PR TITLE
JBPM-8750: Excluding unwanted dependencies

### PR DESCRIPTION
**Pull request by jesuino**
Keycloak deps brought resteasy and then broke all REST services. This PR excludes the unwanted deps.

### CODE REVIEW

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@tomasdavidorg @dgutierr this time failed two test (both selenium):
https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/kie-wb-distributions-pullrequests/lastCompletedBuild/testReport/

**Pull request merged**
