### PR TITLE
[DROOLS-5860] Updating pom

### PR DESCRIPTION
**Pull request by gitgabrio**
@danielezonca @mariofusco @jiripetrlik

see https://issues.redhat.com/browse/DROOLS-5860

This PR 
1) add org.kie:kie-pmml-dependencies (trusty-pmml) to business-central
2) remove old (unused) legacy-pmml kie.conf

### CODE REVIEW

**Comment by gitgabrio** [comment]
Jenkins retest this

**Comment by gitgabrio** [comment]
Jenkins retest this

**Review by danielezonca — APPROVED** [review]

**Review by jiripetrlik — APPROVED** [review]
LGTM

**Comment by gitgabrio** [comment]
@danielezonca Hi! Could you please merge this, squashing commits? Thanks!

**Pull request merged**
