### PR TITLE
BXMSPROD-1272 - reduce GWT Maven plugin compilation classpath

### PR DESCRIPTION
**Pull request by almope**
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>

https://issues.redhat.com/browse/BXMSPROD-1259

### CODE REVIEW

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins execute product fdb

**Comment by almope** [comment]
Jenkins execute product fdb

**Comment by almope** [comment]
jenkins retest this

**Comment by almope** [comment]
jenkins retest this please

**Comment by almope** [comment]
Jenkins execute product fdb

**Comment by almope** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
it seems there is a problem in droolsjbpm-integration repo 
```
[2021-04-12T07:54:30.882Z] Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
[2021-04-12T07:54:30.882Z] /home/jenkins/workspace/KIE/master/pullrequest/kie-wb-distributions-master.pr/bc/kiegroup_droolsjbpm_integration/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/QueryDataServiceBaseTest.java:[59,53] no suitable constructor found for UserTaskInstanceWithPotOwnerDesc(java.lang.String,java.lang.String,java.util.Date,java.util.Date,java.lang.Long,java.lang.String,int,java.lang.Long,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
```

@elguardian @MarianMacik  @gmunozfe any idea why the compilation is broken ?

**Comment by mareknovotny** [comment]
@almope please prepare also backport PR to 7.52.x branch

**Comment by almope** [comment]
It seems that the update in [1], wasn't considered in [2]

[1] https://github.com/kiegroup/jbpm/pull/1903/files#diff-28636253da45daf7b4095c8d0fe9a5fd209e7638c4fcadf225859ae970aab1f5R60
[2] https://github.com/kiegroup/droolsjbpm-integration/blob/master/kie-server-parent/kie-server-services/kie-server-services-jbpm/src/test/java/org/kie/server/services/jbpm/QueryDataServiceBaseTest.java#L61

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins execute product fdb

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins execute product fdb

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Pull request merged**
