### PR TITLE
AF-2125: Adding  dependencies removed from widgets core

### PR DESCRIPTION
**Pull request by jesuino**
Part of an ensemble:

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1066
kiegroup/appformer#807
kiegroup/kie-wb-common#2917
kiegroup/drools-wb#1235
kiegroup/jbpm-wb#1393
https://github.com/kiegroup/optaplanner-wb/pull/347

### CODE REVIEW

**Comment by domhanak** [comment]
jenkins retest this

**Comment by domhanak** [comment]
jenkins retest this

**Comment by domhanak** [comment]
jenkins retest this

**Comment by jesuino** [comment]
jenkins retest this

**Comment by domhanak** [comment]
jenkins retest this

**Comment by jesuino** [comment]
jenkins retest this

**Comment by jesuino** [comment]
jenkins retest this

**Comment by domhanak** [comment]
jenkins retest this

**Comment by domhanak** [comment]
The test is also failing in other PR's.

**Pull request merged**
