### PR TITLE
RHPAM-3066: Error when creating page in Monitoring console

### PR DESCRIPTION
**Pull request by jesuino**
Error when creating page in Monitoring console

[RHPAM-3066](https://issues.redhat.com/browse/RHPAM-3066)

### CODE REVIEW

**Comment by ederign** [comment]
please jenkins execute full downstream build

**Comment by jesuino** [comment]
jenkins execute fdb

**Review by ederign — APPROVED** [review]

**Comment by jesuino** [comment]
jenkins execute fdb

**Comment by mareknovotny** [comment]
fyi @ederign, here the FDB doesn't make sense as the kie-wb-distributions repository is at the end of the repository chain

**Review by tomasdavidorg — APPROVED** [review]

**Pull request merged**
