### PR TITLE
JBPM-10083 : Legacy (jBPM) Process Designer Removal

### PR DESCRIPTION
**Pull request by inodeman**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://issues.redhat.com/browse/JBPM-10083)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
https://github.com/kiegroup/kie-wb-common/pull/3743
(Takes care of migration of bpmn2 files within Stunner)

https://drive.google.com/drive/folders/195afqwca3fw7Bg-48wK3XmSa7bxJCRtD?usp=sharing
(War file)
* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by romartin** [comment]
Hey @LuboTerifaj 

This PR it is a top priority for the release. Could you please prioritize it properly and take a look as soon as possible plz?
Remember it is related to https://github.com/kiegroup/kie-wb-common/pull/3743

Thanks in advance!

**Review by romartin — APPROVED** [review]

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @inodeman ,

please see my: https://github.com/kiegroup/kie-wb-common/pull/3743#pullrequestreview-1047868367

Thanks!

**Review by LuboTerifaj — APPROVED** [review]
Approving according to https://github.com/kiegroup/kie-wb-common/pull/3743#pullrequestreview-1057516929

**Comment by romartin** [comment]
Do **NOT merge until** https://github.com/kiegroup/kie-wb-common/pull/3743 is also merged.

**Comment by mareknovotny** [comment]
shouldn't those changes be send to ONLY 7.67.x-blue branch? @lazarotti

**Comment by romartin** [comment]
@mareknovotny hey, as we discussed also with @lazarotti those changes will be present on both main and ibm branches. So we still have to cherry-pick this to ibm related branches after merging here.

**Comment by romartin** [comment]
Waiting for merge confirmation, see https://github.com/kiegroup/kie-wb-common/pull/3743#issuecomment-1204458044

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by inodeman** [comment]
Jenkins retest this

**Comment by inodeman** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
no need to launch here FDB as kie-wb-distribution repo is the end so PR job is the same as FDB.

All green it seems even on parent PR for FDB and CI so we can merge

**Comment by Ginxo** [comment]
Hi guys @inodeman @romartin 

shouldn't stunner dependencies from https://github.com/kiegroup/kie-wb-distributions/blob/297701ae01866c96c386d17a16466725fbea8820/business-central-parent/business-central-webapp/pom.xml#L2162 be deleted?
what about these additional lines:
* https://github.com/kiegroup/kie-wb-distributions/blob/297701ae01866c96c386d17a16466725fbea8820/business-central-parent/business-central-distribution-wars/business-central/scripts/set-rhdm-props.cli#L2
* https://github.com/kiegroup/kie-wb-distributions/blob/297701ae01866c96c386d17a16466725fbea8820/business-central-parent/business-central-distribution-wars/src/main/productized/standalone/project-defaults.yml#L5
* https://github.com/kiegroup/kie-wb-distributions/blob/297701ae01866c96c386d17a16466725fbea8820/business-central-parent/business-central-webapp/src/main/java/org/kie/bc/backend/AppSetup.java#L112 & https://github.com/kiegroup/kie-wb-distributions/blob/297701ae01866c96c386d17a16466725fbea8820/business-central-parent/business-central-webapp/src/main/java/org/kie/bc/backend/AppSetup.java#L114

@mareknovotny FYI

**Comment by LuboTerifaj** [comment]
Hello @Ginxo I think those dependencies are needed for legacy processes migration to Stunner.

**Comment by Ginxo** [comment]
According to private conversation with @inodeman those stunner will included on a second PR.
@inodeman please consider he is preparing. Closing https://github.com/kiegroup/kie-wb-distributions/pull/1184

**Pull request merged**
