### PR TITLE
BXMSPROD-830 add scopes to missing backend dependencies

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-830
You can see the result here https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/PROD/job/nightly/view/change-requests/job/PR-1367/20/console

### CODE REVIEW

**Comment by mareknovotny** [comment]
Please verify carefully this fix as it was a followup on blocker fix https://github.com/kiegroup/kie-wb-distributions/pull/1038 which added too many deps into maven build and broke our CI due that
@tomasdavidorg @RishiRajAnand

**Comment by Ginxo** [comment]
Jenkins retest this please

**Comment by almope** [comment]
Jenkins retest this please

**Comment by almope** [comment]
Jenkins retest this please

**Comment by Ginxo** [comment]
gwt is also working https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/PROD/job/nightly/view/change-requests/job/PR-1367/22/console

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by Ginxo** [comment]
Jenkins retest this please

**Pull request merged**
