### PR TITLE
Library UX/UI improvements

### PR DESCRIPTION
**Pull request by paulovmr**
AF-636: UX/UI improvements on spaces (teams) screen
AF-892: UX/UI improvements on projects screen

### CODE REVIEW

**Comment by paulovmr** [comment]
Part of an ensemble:
* https://github.com/AppFormer/uberfire/pull/910
* https://github.com/kiegroup/kie-wb-common/pull/1289
* https://github.com/kiegroup/kie-wb-distributions/pull/652

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by ederign** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Pull request merged**
