### PR TITLE
Use rerunFailingTestsCount for BC integration test

### PR DESCRIPTION
**Pull request by domhanak**
@tomasdavidorg @jomarko Adding it here as I see the selenium tests failing in common fashion, this is a test to see if it helps.

### CODE REVIEW

**Comment by domhanak** [comment]
```
07:22:42 [WARNING] org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded(org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest)
07:22:42 [ERROR]   Run 1: LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded:36 » ElementClickIntercepted
07:22:42 [INFO]   Run 2: PASS
```

**Comment by domhanak** [comment]
@tomasdavidorg updated

**Comment by tomasdavidorg** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
@kiegroup/gatekeepers could someone please review and merge if ok?

**Pull request merged**
