### PR TITLE
[DROOLS-3389]: Added missing dependency

### PR DESCRIPTION
**Pull request by adrielparedes**
@manstis @gitgabrio @danielezonca guys, I had that dependency because I couldn't compile business-central-webapp without it.

Would you mind to review it?

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins please retest this

**Comment by danielezonca** [comment]
jenkins retest this please

**Comment by danielezonca** [comment]
jenkins please retest this

**Comment by manstis** [comment]
> _Daniele Zonca_
> I think it is safe to merge, wdyt?

I agree.

**Pull request merged**
