### PR TITLE
KOGITO-7179 : Business Central usage of resource.getContextPath() is insecure

### PR DESCRIPTION
**Pull request by Rikkola**
[KOGITO-7179](https://issues.redhat.com/browse/KOGITO-7179)

[ZIP](https://drive.google.com/file/d/1zIhk_nHztSZqG6fOdSvbcB7TJUlrz9uL/view?usp=sharing)

[WAR](https://drive.google.com/file/d/1W9fr_1jPMoX6GURgnLpkUhmhk6QbGTQX/view?usp=sharing)

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Rikkola** [comment]
```
[2022-08-05T14:32:37.165Z] [WARNING] The requested profile "run-code-coverage" could not be activated because it does not exist.
[2022-08-05T14:32:37.165Z] [ERROR] Failed to execute goal org.codehaus.cargo:cargo-maven3-plugin:1.9.3:start (start-container) on project business-central-tests-rest: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly23xInstalledLocalContainer@7c6fd5b7]: Deployable [http://localhost:43562/business-central] failed to finish deploying within the timeout period [90000]. The Deployable state is thus unknown. -> [Help 1]
[2022-08-05T14:32:37.165Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.cargo:cargo-maven3-plugin:1.9.3:start (start-container) on project business-central-tests-rest: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly23xInstalledLocalContainer@7c6fd5b7]
```

Jenkins retest this

**Comment by Rikkola** [comment]
```
[2022-08-08T09:55:17.339Z] [ERROR] Failed to execute goal org.codehaus.cargo:cargo-maven3-plugin:1.9.3:start (start-container) on project business-central-tests-rest: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly23xInstalledLocalContainer@662d5f38]: Deployable [http://localhost:38670/business-central] failed to finish deploying within the timeout period [90000]. The Deployable state is thus unknown. -> [Help 1]
[2022-08-08T09:55:17.339Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.cargo:cargo-maven3-plugin:1.9.3:start (start-container) on project business-central-tests-rest: Cannot start container [org.codehaus.cargo.container.wildfly.WildFly23xInstalledLocalContainer@662d5f38]
```
Same one twice, I need to try locally.

**Comment by Rikkola** [comment]
Jenkins run fdb

**Comment by domhanak** [comment]
jenkins test this

**Comment by Rikkola** [comment]
jenkins test this

**Comment by Rikkola** [comment]
SO IT IS POSSIBLE TO GET BOTH GREEN! :D 🥳

**Review by mbiarnes — APPROVED** [review]
LGTM

**Comment by domhanak** [comment]
LGTM, I tried basic login use cases to verify everything still works, also run almost whole UI test suite dependent on these changes and did not see any failures there so :green_circle: to merge. Thanks @Rikkola

**Review by domhanak — APPROVED** [review]
Feel free to merge if builds are green.

**Pull request merged**
