### PR TITLE
Remove double '*' pattern (doesn't work in Tomcat).

### PR DESCRIPTION
**Pull request by mbarkley**
@manstis I'm fairly certain this will fix the build issue with Tomcat caused by my previous PR.

@psiroky Is there a quick way to test this? I don't have Tomcat setup locally.

### CODE REVIEW

**Comment by psiroky** [comment]
@mbarkley you should be able to run the kie-wb-tests locally on Tomcat with something like `mvn clean verify -Pkie-wb,tomcat8`

**Comment by mbarkley** [comment]
@psiroky Thanks. Giving that a try now.

**Comment by mbarkley** [comment]
@manstis Yeah the `*.cache.html` pattern just in case we ever switch GWT linkers (one of them generates HTML files with JS in them instead of JS files).

**Comment by mbarkley** [comment]
@manstis Well it still fails locally. This time "/org.kie.workbench.KIEWebapp/*.cache.js" is an invalid url constraint.

I will continue investigating solutions.

**Comment by mbarkley** [comment]
@manstis I've discovered the [error](https://stackoverflow.com/a/26744/3091732) of my ways. I've run the tests locally with Tomcat to verify this change fixes this problem.

**Pull request merged**
