### PR TITLE
JBPM-8243 - Decrease Business Central logo height

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by jstastny-cz** [comment]
If we just replace the images then the height of the top bar shrinks accordingly.

The image height decreased by 17 px.
The resulting height of #megamenu is decreased by 14 px (when swapping the images). Thus there's 3 px more room in the bar for the image not to overflow.

I wasn't able to reproduce the original issue on 7.17.0.Final on Firefox nor Chrome.

**Comment by cristianonicolai** [comment]
@manstis @jstastny-cz I can reproduce this issue using:
- Chrome Version 72.0.3626.109 (Official Build) (64-bit)
- jbpm-server-7.17.0.Final-dist

**Comment by jstastny-cz** [comment]
@cristianonicolai @nmirasch alright then. Thanks for the effort.

**Comment by jstastny-cz** [comment]
The build has failed due issue being resolved in https://github.com/kiegroup/appformer/pull/636 .

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
