### PR TITLE
GUVNOR-3237: Change the home page to the new one

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
Part of an ensemble:
* https://github.com/kiegroup/kie-wb-common/pull/993
* https://github.com/kiegroup/drools-wb/pull/558
* https://github.com/kiegroup/jbpm-form-modeler/pull/124
* https://github.com/kiegroup/optaplanner-wb/pull/190
* https://github.com/kiegroup/kie-wb-distributions/pull/560

**Comment by paulovmr** [comment]
@manstis Fixed the selenium tests, thanks for the reminder ;). Actually I removed one of the separate modules (the bigger one), we still have `kie-wb-home-page-product` and `kie-drools-wb-home-page-product` to differentiate background and texts between community and product versions.

**Comment by manstis** [comment]
Thanks @paulovmr that's what I meant (removal of the shadowing ```HomeModel``` module).

**Comment by paulovmr** [comment]
I will make some small changes on this PR and the related ones (texts and ids on html), so please don't rebuild/merge them yet.

**Comment by paulovmr** [comment]
Ok, good to merge for me.

**Pull request merged**
