### PR TITLE
Remove Angular and Knockout from Business Central War

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by ederign** [comment]
please jenkins restest this

**Comment by tomasdavidorg** [comment]
There are still some occurrences:
- https://github.com/search?q=org%3Akiegroup+angular&type=Code
- https://github.com/search?q=org%3Akiegroup+knockout&type=Code
What about them? We should probably remove them too.

**Comment by ederign** [comment]
Hi @tomasdavidorg I keep the engine on uberfire and uberfire extensions, but the angular code are not exposable on business central.
I think in future we can still use this extension mechanism somehow (after updating angular).

But i'm open to remove anything. I will defer this decision to @porcelli

**Comment by ederign** [comment]
please jenkins retest this

**Comment by mareknovotny** [comment]
please backport this to 7.26.x branch too. See what linked jiras are in https://issues.jboss.org/browse/AF-2292

**Pull request merged**
