### PR TITLE
[RHPAM-4618] update EAP XP to version 4.0.0.GA-redhat-00011

### PR DESCRIPTION
**Pull request by rgdoliveira**
This prod version is EAP XP on top of EAP 7.4.8

**JIRA**:  https://issues.redhat.com/browse/RHPAM-4618

**referenced Pull Requests**: 
- https://github.com/kiegroup/kie-wb-distributions/pull/1208
- https://github.com/kiegroup/kie-wb-distributions/pull/1206
- https://github.com/kiegroup/kie-wb-distributions/pull/1207

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by rgdoliveira** [comment]
Jenkins run fdb

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
Jenkins execute product fdb

**Review by tomasdavidorg — APPROVED** [review]
I built it locally and did some testing and it looks good to me. 🙂 Thanks.

**Comment by rgdoliveira** [comment]
Execution Summary:
```
[2022-12-08T12:25:45.019Z] ::group::[Full Downstream Flow] Execution Summary...
[2022-12-08T12:25:45.019Z] [INFO]  ----------------------------------------------
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/droolsjbpm-build-bootstrap]. Execution Result: ok. Time: 10.2s (10277 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/kie-soup]. Execution Result: ok. Time: 1m 21.3s (81308 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/droolsjbpm-knowledge]. Execution Result: ok. Time: 27.7s (27764 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/drools]. Execution Result: ok. Time: 21m 23.3s (1283317 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/optaplanner]. Execution Result: ok. Time: 4m 2.4s (242423 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/lienzo-core]. Execution Result: ok. Time: 8s (8048 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/lienzo-tests]. Execution Result: ok. Time: 29.4s (29453 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/appformer]. Execution Result: ok. Time: 15m 40.5s (940534 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/kie-uberfire-extensions]. Execution Result: ok. Time: 4.6s (4617 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/jbpm]. Execution Result: ok. Time: 41m 58.3s (2518309 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/droolsjbpm-integration]. Execution Result: ok. Time: 28m 9.1s (1689155 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/kie-wb-playground]. Execution Result: ok. Time: 12.9s (12993 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/kie-wb-common]. Execution Result: ok. Time: 28m 12.9s (1692944 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/drools-wb]. Execution Result: ok. Time: 19m 43.5s (1183561 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/jbpm-work-items]. Execution Result: ok. Time: 10m 45.6s (645609 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/jbpm-wb]. Execution Result: ok. Time: 11m 10.4s (670438 ms)
[2022-12-08T12:25:45.019Z] [INFO]  [kiegroup/optaplanner-wb]. Execution Result: error. Time: 1m 21.1s (81162 ms)
[2022-12-08T12:25:45.019Z] [INFO]  ----------------------------------------------
```

FDPB failed with non related error to kie-wb-distributions
```
[2022-12-08T12:25:12.999Z] [INFO] Compiling module org.optaplanner.workbench.OptaPlannerWorkbench
[2022-12-08T12:25:45.019Z] [INFO]    Tracing compile failure path for type 'org.kie.workbench.common.screens.library.client.screens.project.ProjectMetricsScreen'
[2022-12-08T12:25:45.019Z] [INFO]       [ERROR] Errors in 'jar:file:/home/jenkins/.m2/repository/org/kie/workbench/screens/kie-wb-common-library-client/7.74.0-SNAPSHOT/kie-wb-common-library-client-7.74.0-SNAPSHOT-sources.jar!/org/kie/workbench/common/screens/library/client/screens/project/ProjectMetricsScreen.java'
[2022-12-08T12:25:45.019Z] [INFO]          [ERROR] Line 77: No source code is available for type org.kie.workbench.common.screens.contributors.service.ContributorsService; did you forget to inherit a required module?
[2022-12-08T12:25:45.019Z] [INFO]    Tracing compile failure path for type 'org.kie.workbench.common.screens.library.client.screens.OrgUnitsMetricsScreen'
[2022-12-08T12:25:45.019Z] [INFO]       [ERROR] Errors in 'jar:file:/home/jenkins/.m2/repository/org/kie/workbench/screens/kie-wb-common-library-client/7.74.0-SNAPSHOT/kie-wb-common-library-client-7.74.0-SNAPSHOT-sources.jar!/org/kie/workbench/common/screens/library/client/screens/OrgUnitsMetricsScreen.java'
[2022-12-08T12:25:45.019Z] [INFO]          [ERROR] Line 100: No source code is available for type org.kie.workbench.common.screens.contributors.service.ContributorsService; did you forget to inherit a required module?
```

**Pull request merged**
