### PR TITLE
AF-1787 - Integrate AppFormer.js on Business Central

### PR DESCRIPTION
**Pull request by tiagobento**
On this PR:

- Configuration of new AppFormer.js component Spaces Screen for both `business-central-webapp` and `business-monitoring-webapp`

Related PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/936
https://github.com/kiegroup/appformer/pull/662
https://github.com/kiegroup/kie-wb-common/pull/2526
https://github.com/kiegroup/drools-wb/pull/1090
https://github.com/kiegroup/jbpm-wb/pull/1314
https://github.com/kiegroup/optaplanner-wb/pull/329
https://github.com/kiegroup/kie-wb-distributions/pull/893

### CODE REVIEW

**Comment by tiagobento** [comment]
Jenkins, please retest this.

**Comment by tiagobento** [comment]
Jenkins, please retest this.

**Comment by tiagobento** [comment]
@domhanak Just commented on kiegroup/kie-wb-common#2526. I'll add the integration tests here.

**Comment by tiagobento** [comment]
@domhanak Tests were added on 9e3531a. I'm working on the FDB at kiegroup/appformer#662 now.

**Comment by domhanak** [comment]
Jenkins retest this

**Comment by tiagobento** [comment]
Jenkins please retest this

**Comment by tiagobento** [comment]
Jenkins please retest this

**Pull request merged**
