### PR TITLE
JBPM-8337 - Use basic authentication to avoid web session creation fo…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…r REST and WebSocket connections

Assembly:
https://github.com/kiegroup/kie-wb-distributions/pull/895
https://github.com/kiegroup/kie-wb-common/pull/2529
https://github.com/kiegroup/jbpm-wb/pull/1315

### CODE REVIEW

**Comment by cristianonicolai** [comment]
@manstis @ederign @porcelli any potential drawback in not using the appformer login service? This actually avoids creating sessions for REST requests as well. It only works for Wildfly/EAP but that I think it is ok.

**Comment by porcelli** [comment]
I honestly don't know, this has been around forever... it looks fine, tho.

including @domhanak @tomasdavidorg @barboras7

**Comment by tomasdavidorg** [comment]
@cristianonicolai Do you know how this involve the SSO integration? We have steps how to setup that: https://github.com/kiegroup/kie-docs/blob/master/doc-content/shared-kie-docs/src/main/asciidoc/Workbench/KeycloakSSOIntegration/KC_SSO_integ-section.adoc

Will the setup work (with some update) after these changes?

**Comment by cristianonicolai** [comment]
@tomasdavidorg I would expect it to work mainly because the changes I'm proposing here take th.e same steps as listed in the docs. The only real difference I can see is the use of _rest-all_ role. That should probably be the default here, instead of any role. @porcelli wdyt?

**Comment by cristianonicolai** [comment]
@Rikkola would you be able to check if this has any impact in swarm somehow?

**Comment by cristianonicolai** [comment]
@manstis any concerns from your side regarding this change?

**Comment by manstis** [comment]
@cristianonicolai TBH I can only guess at the affect this could have elsewhere.

However given the comments and approval by others I have no objection.

**Comment by Rikkola** [comment]
@cristianonicolai I'll need to build the Swarm jar locally and even then I will only be able to test the default login. I'll compile it tonight.

**Comment by cristianonicolai** [comment]
@manstis @Rikkola thanks

**Comment by cristianonicolai** [comment]
@mswiderski fyi, this will require that _kieserver_ user has at least one valid role in BC for the connection with the controller to work.

**Comment by cristianonicolai** [comment]
@Rikkola thanks

**Comment by sutaakar** [comment]
@errantepiphany This PR probably affects also Workbench images. Changes in web.xml need to be reflected on the image script side.

**Comment by errantepiphany** [comment]
@sutaakar Thanks so much for this. We were actually just noticing some weird stuff with websockets and auth yesterday, so this is definitely something we should review as it sounds related.

**Comment by cristianonicolai** [comment]
@errantepiphany let me know if you need any help/details about this change.

**Pull request merged**
