### PR TITLE
JBPM-8470 - Add rest-all role and secure REST related endpoints

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by sutaakar** [comment]
@cristianonicolai Is this PR ready to be reviewed? The issue is blocking significant amount of cloud tests and complicates our testing.

**Comment by cristianonicolai** [comment]
@sutaakar sure, I had to make some changes to make sure tests were stable but looks good for review now.

**Comment by cristianonicolai** [comment]
Reverting blocking change on https://github.com/kiegroup/kie-wb-distributions/pull/925 for now.

**Pull request closed without merging**
