### PR TITLE
[7.59.x] JBPM-9896 - Fix dependency for compilation Stunner on JDK 11 to JRE 8

### PR DESCRIPTION
**Pull request by hasys**
Hi @mareknovotny, @mbiarnes, @romartin, @jomarko it is cherry-pick of https://github.com/kiegroup/kie-wb-distributions/pull/1127

**referenced Pull Requests**: 

* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1771
* https://github.com/kiegroup/kie-wb-distributions/pull/1129
* https://github.com/kiegroup/jbpm-wb/pull/1515
* https://github.com/kiegroup/kie-wb-common/pull/3685

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by jomarko — APPROVED** [review]

**Review by mbiarnes — APPROVED** [review]
+1

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by hasys** [comment]
Build failing due to unrelated test:

<details>
  <summary>Click to expand</summary>
  <pre>org.kie.bc.DeploymentIT.org.kie.bc.DeploymentIT</pre>
</details>

This test is known as unstable, I suggest to not restart the build anymore. @mareknovotny, @mbiarnes, @romartin, @jomarko  WDYT?

**Review by romartin — APPROVED** [review]

**Pull request merged**
