### PR TITLE
JBPM-6149: Teams metrics dashboard

### PR DESCRIPTION
**Pull request by dgutierr**
Depends on https://github.com/kiegroup/kie-wb-common/pull/958

### CODE REVIEW

**Comment by dgutierr** [comment]
Jenkins execute full downstream build

**Comment by dgutierr** [comment]
Jenkins execute full downstream build

**Comment by dgutierr** [comment]
@paulovmr @jhrcek Can you review it please?

**Comment by dgutierr** [comment]
Jenkins execute full downstream build

**Comment by dgutierr** [comment]
Jenkins execute full downstream build

**Comment by manstis** [comment]
@dgutierr The "full downstream build" will fail due to ```ExecutorService``` and consequentially failing REST tests in ```kie-wb-distributions\kie-wb-tests```.. Please see BSIG mailing list about the issue.

**Comment by dgutierr** [comment]
@manstis This is targeted for 7.1. Can you please merge?

**Comment by manstis** [comment]
@dgutierr I can.. but who's investigating the failed Selenium test? We know the REST-related failing tests are being resolved by @adrielparedes but what about the Selenium one?

**Comment by dgutierr** [comment]
@manstis I'd expect @jhrcek having a look at it. The failing test it does not seem related to this PR though. I'm wondering other PRs might have similar issue.

**Comment by dgutierr** [comment]
Jenkins execute full downstream build

**Comment by paulovmr** [comment]
Unfortunatelly the build (compilation) is now broken on master because the related PR was merged and this wasn't. :(

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Failures are the know REST issue that @adrielparedes is fixing; and a Selenium Test that looks to be a time-out issue (```Command duration or timeout: 63 milliseconds```).. so merging or I will fee the wrath of @paulovmr 

@dgutierr @paulovmr IF PRs have to be merged at the same time, please do not simply say something _depends_ on another as it does not really mean that they _must_ be merged together.

**Pull request merged**
