### PR TITLE
RHPAM-1862: fix disabling case modeller in security policy

### PR DESCRIPTION
**Pull request by xiezhang7**

### CODE REVIEW

**Comment by xiezhang7** [comment]
Hi @romartin @krisv @hasys @LuboTerifaj , pull request is created for [RHPAM-1862](https://issues.jboss.org/browse/RHPAM-1862). Thanks.

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Comment by hasys** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
great, thanks guys! Merging

**Comment by romartin** [comment]
@xiezhang7 can you please create a JBPM ticket and cherry-pick this change to master branch as well? Thanks!

**Comment by xiezhang7** [comment]
> @xiezhang7 can you please create a JBPM ticket and cherry-pick this change to master branch as well? Thanks!

Hi @romartin , [pull request](https://github.com/kiegroup/kie-wb-distributions/pull/897) and ticket [JBPM-8345](https://issues.jboss.org/browse/JBPM-8345) created for master branch. Thanks.

**Pull request merged**
