### PR TITLE
RHPAM-1205 Loading application... pop up is garbled in locale=ja

### PR DESCRIPTION
**Pull request by bxf12315**
@cristianonicolai Please review it.

### CODE REVIEW

**Comment by manstis** [comment]
This will be override the next time translations are fetched from Zanata. Unfortunately this is a fix for the symptoms  of the cause. Where are the Japanese translations garbled? Following a build with -Dfull?

**Comment by bxf12315** [comment]
@manstis It different to other Constants files, it's using in jsp page.
I find some explanation from  stackoverflow. https://stackoverflow.com/questions/28026342/internationalization-using-resource-bundle-properties-in-jsp-non-latin-text-bec

**Comment by manstis** [comment]
@bxf12315 Hi, if you look at the commit you mentioned (when the file was last updated) you'll see the PR is titled "latest Zanata translation changes in kie-wb-distributions from 2019-01-25".. i.e. the i18n'ed text came from Zanata and hence when this is next performed your changes here will again be overwritten.

The files from Zanata are updated to UTF-8 by [this](https://github.com/kiegroup/kie-wb-distributions/blob/master/pom.xml#L194) however it appears to be missing the specific entries for the "Product Home Page" (and no doubt Community too).

I'd suggest updating the `native2ascii-maven-plugin` plugin configuration and trying a `mvn clean install -Dfull` and check the resulting `Constants_ja.properties` has the correct encoding.

**Comment by cristianonicolai** [comment]
Closing as it has been fixed by https://github.com/kiegroup/kie-wb-distributions/pull/892

**Pull request closed without merging**
