### PR TITLE
Remove Dash Boards permission for Product Home Page

### PR DESCRIPTION
**Pull request by manstis**
@mbiarnes This should fix compilation for the "product" Home Page.

@dgutierr This was the simplest solution.. please check whether permission is still required.

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by mbiarnes** [comment]
@dgutierr please check and ack it - so it can be merged

**Comment by dgutierr** [comment]
+1

**Pull request merged**
