### PR TITLE
RHBPMS-4583: User can perform process instance specific operations. R…

### PR DESCRIPTION
**Pull request by nmirasch**
…estored permissions for the role user.
Allow the access to process definitions and process instances perspectives for the role user.

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins retest this

**Comment by cristianonicolai** [comment]
@nmirasch should the role user have access to process instance and definition perspectives? If we do allow, then thee is need to block the process operations for this role as mentioned in the JIRA.

**Comment by nmirasch** [comment]
@cristianonicolai I think, the jira was related to add the control and when the user role don't have access to those perspectives, block that link to them. Currently, if the configuration don't want allow the user could perform process operations, the permission have to block those perspectives and the link from task list would appear as disabled. (At least that was what Kris mentioned ) Do you think that makes sense? I understand that we have to modify the role user default permissions in the distribution, but the jira only was referred to react to those permission, and that's the reason for revert this change.

**Comment by nmirasch** [comment]
jenkins retest this

**Pull request merged**
