### PR TITLE
DROOLS-2846 : Move Verifier core from drools-wb to drools

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-2846
https://issues.jboss.org/browse/DROOLS-2847

Pretty much just moving code for the 99% of the changes and then 1% of refactorings to make the move easier.

Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/800
https://github.com/kiegroup/drools/pull/2021
https://github.com/kiegroup/kie-wb-common/pull/2054
https://github.com/kiegroup/drools-wb/pull/916
https://github.com/kiegroup/optaplanner-wb/pull/301
https://github.com/kiegroup/kie-wb-distributions/pull/795

### CODE REVIEW

**Comment by Rikkola** [comment]
jenkins please execute full downstream build

**Comment by Rikkola** [comment]
jenkins please execute full downstream build

**Comment by Rikkola** [comment]
jenkins please execute full downstream build

**Comment by jomarko** [comment]
Strange, you asked 3 hours ago but still not started, jenkins has too much work probably. Lets wait more.

**Comment by Rikkola** [comment]
I also accidentally closed the PR, reopened and then asked. Not sure if this affects the build.

**Comment by Rikkola** [comment]
jenkins please execute full downstream build

**Comment by Rikkola** [comment]
jenkins please execute full downstream build

**Comment by Rikkola** [comment]
Maybe the normal run works. Jenkins please retest this.

**Comment by Rikkola** [comment]
Looks like optaplanner-wb needs an update.

**Comment by Rikkola** [comment]
Jenkins please retest this.

**Comment by Rikkola** [comment]
jenkins please restart this 
"Unexpected error while executing the Upstream repositories builder for PR builds!"

**Comment by Rikkola** [comment]
Failed to execute goal on project kie-server-integ-tests-common: Could not resolve dependencies for project org.kie.server:kie-server-integ-tests-common:jar:7.11.0-SNAPSHOT: Failed to collect dependencies at org.codehaus.cargo:cargo-core-uberjar:jar:1.6.9

jenkins please restart this

**Comment by Rikkola** [comment]
jenkins please restart this

**Comment by Rikkola** [comment]
jenkins please restart this

**Comment by Rikkola** [comment]
jenkins please retest this

**Comment by Rikkola** [comment]
@manstis Good day. This finally turned green so if you would be kind enough to merge it in please. Thank you.

**Pull request merged**
