### PR TITLE
JBPM-7609: integrate Case Mgmt into Workbench

### PR DESCRIPTION
**Pull request by jeremyary**
Second attempt of kie-wb-distributions PR for integrating CM into workbench, now with matching kie-wb-common PR that's also been pushed out for review.

### CODE REVIEW

**Comment by manstis** [comment]
ok to test.

**Comment by manstis** [comment]
@jomarko There should be a new permission that disables creation of Case Models by default. If it is enabled then Users should be able to create a new Case Model from the Library screens.

**Comment by jomarko** [comment]
I will have a look once dependency problem resolved in https://github.com/kiegroup/kie-wb-common/pull/1775

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser3** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by jeremyary** [comment]
Jenkins please retest this

**Pull request merged**
