### PR TITLE
[7.18.x] AF-1876 : Full profile is the default profile in Swarm RHDM distribution

### PR DESCRIPTION
**Pull request by Rikkola**
(cherry picked from commit f32ab185256709eee29b050189d212db1aeb4a80)

https://issues.jboss.org/browse/AF-1876

@tomasdavidorg @mareknovotny if you two could please take a look.

### CODE REVIEW

**Comment by Rikkola** [comment]
To test use -Dproducized when building.

**Comment by tomasdavidorg** [comment]
I built and tested the jars locally and it looks good to me. Thanks :slightly_smiling_face:

**Comment by Rikkola** [comment]
I hear @AntStephenson is also taking a look.

**Comment by AntStephenson** [comment]
Looks good to me, thank you @Rikkola !

**Comment by Rikkola** [comment]
@kiegroup/gatekeepers This is ready to be merged then.

**Comment by manstis** [comment]
@Rikkola glad to see you're still the Swarm king! ;-)

**Comment by Rikkola** [comment]
@manstis I doubt this or many other king-roles I have will ever go away ;)

**Pull request merged**
