### PR TITLE
[7.67.x-blue][RHPAM-4379] rebrand RHPAM to IBM Business Automation Manager

### PR DESCRIPTION
**Pull request by rgdoliveira**
https://issues.redhat.com/browse/RHPAM-4379

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by rgdoliveira** [comment]
The following image need to be replaced:
- business-central-parent/business-central-distribution-wars/src/main/productized/webapp/favicon.png

**Review by Ginxo — APPROVED** [review]
LGTM

**Comment by mareknovotny** [comment]
we as Productization team decided yesterday to replace only branding and texts in RHPAM productization profile to get simple solution to have very the same content and backporting easy in future if needed.

**Review by tomasdavidorg — COMMENTED** [review]
Hi, I checked the new branding in Chrome and Firefox browsers and I have few comments:

- Favicon is vertically deformed because its height is not equal to its width. 
  - Firefox
Screenshot from 2022-06-07 13-00-20
  - Chrome
Screenshot from 2022-06-07 12-59-54

- Login page inputs collide with the background logo.
Screenshot from 2022-06-07 13-28-21
Screenshot from 2022-06-07 13-28-54
Screenshot from 2022-06-07 13-29-09
- Texts above the background stripped IBM logo are hard to read. Even the screen is resized.
Screenshot from 2022-06-07 13-29-44
Screenshot from 2022-06-07 13-30-34
- Same visual issue in the about dialog.
Screenshot from 2022-06-07 13-30-59

**Comment by rgdoliveira** [comment]
Thanks for the review @tomasdavidorg. I've replaced the Favicon and it is not deformed anymore.

Regarding the background logo, do you have any suggestions @mareknovotny ?

**Comment by rgdoliveira** [comment]
> from my POV it is ok as the background logo is what they provided. Maybe we can merge it and send them the nightly result if it is ok ? @tomasdavidorg @rgdoliveira wdyt?

+1 from me. We can replace the background logo later if it is required.

**Comment by tomasdavidorg** [comment]
@rgdoliveira Thanks for the fix
@mareknovotny Ok. If it is provided then we can merge it.

**Review by AntStephenson — APPROVED** [review]

**Review by jomarko — COMMENTED** [review]
Could someone please recheck also DMN Documentation tab?
Screenshot from 2022-06-07 16-30-18

**Comment by rgdoliveira** [comment]
> Could someone please recheck also DMN Documentation tab? Screenshot from 2022-06-07 16-30-18

I didn't find any occurrence of DMN Documentation tab in kie-wb-distributions project.
I suppose it is a different repository? Also, is it part of the deliverables distributed with the product?

**Comment by mareknovotny** [comment]
> Could someone please recheck also DMN Documentation tab? Screenshot from 2022-06-07 16-30-18

Could you reference the filename of the image? if it is not in this repository we need to find it elsewhere and without filename it is not possible. @jomarko

**Comment by jomarko** [comment]
**Workbench**
- https://github.com/kiegroup/kie-wb-common/tree/main/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/images/logos
- https://github.com/kiegroup/kie-wb-common/blob/main/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/resources/DMNImageResources.java#L49


**Kogito**
- https://github.com/kiegroup/kie-tools/tree/main/packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/resources/org/kie/workbench/common/dmn/client/resources/images/logos
- https://github.com/kiegroup/kie-tools/blob/main/packages/stunner-editors/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/resources/DMNImageResources.java#L49

**Comment by mareknovotny** [comment]
ok, thanks @jomarko. We don't change Kie tooling at all, so need to change kie-wb-common only

**Comment by mareknovotny** [comment]
so i will merge this and the following logo change can be done independently.

**Comment by mareknovotny** [comment]
just ftr the followed up change in DMN editor was done in https://github.com/kiegroup/kie-wb-common/pull/3741

**Pull request merged**
