### PR TITLE
DROOLS-2535 : Standalone Authoring - Project Explorer should not showup with StandaloneAuthoringPerspective

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-2535

### CODE REVIEW

**Comment by Rikkola** [comment]
@tomasdavidorg Hi, you might want to review this.

**Comment by Rikkola** [comment]
Not sure if my changes can break these tests, so rerunning.

Jenkins please retest.

    org.kie.wb.selenium.ui.LoginIntegrationTest.org.kie.wb.selenium.ui.LoginIntegrationTest
    org.kie.wb.test.rest.security.ProjectAccessIntegrationTest.org.kie.wb.test.rest.security.ProjectAccessIntegrationTest
    org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded
    org.kie.wb.selenium.ui.LoadAllPerspectivesIntegrationTest.allPerspectivesCanBeLoaded
    org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.importAndBuildProjectFromStockRepository

**Comment by jhrcek** [comment]
It's very likely these changes might have affected those tests. But your rerun failed with:
```
 [ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): Access denied to: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.5/maven-resources-plugin-2.5.pom , ReasonPhrase:Forbidden. -> [Help 1]
```

Trying again.. jenkins retest this

**Comment by Rikkola** [comment]
Only 
org.kie.wb.selenium.ui.LoginIntegrationTest.org.kie.wb.selenium.ui.LoginIntegrationTest
showed up.

jenkins retest this.

**Comment by jhrcek** [comment]
@Rikkola that kind of failure is a mystery for me. For some reason the firefox started by selenium tests fails to start. I have yet to understand why..

**Comment by Rikkola** [comment]
Yeah, I think I have seen this quite often. One of those issues that are hard to fix I guess.

**Comment by Rikkola** [comment]
jenkins retest this.

**Comment by Rikkola** [comment]
jenkins retest this.

org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest.org.kie.wb.selenium.ui.ProjectLibraryIntegrationTest
    org.kie.wb.test.rest.functional.ProjectIntegrationTest.org.kie.wb.test.rest.functional.ProjectIntegrationTest
    org.kie.wb.test.rest.security.ProjectAccessIntegrationTest.org.kie.wb.test.rest.security.ProjectAccessIntegrationTest

**Comment by Rikkola** [comment]
It is green!
@manstis or who ever can merge it please do it fast! ;-) Not really that urgent.

**Pull request merged**
