### PR TITLE
PLANNER-350: Workbench: scoreHolder support in Guided Rule Editor

### PR DESCRIPTION
**Pull request by mcimbora**
- Add definitions of optaplanner-wb-guided-rule-editor modules

Part of:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/425
https://github.com/kiegroup/drools/pull/1178
https://github.com/kiegroup/drools-wb/pull/433
https://github.com/kiegroup/optaplanner-wb/pull/143
https://github.com/kiegroup/kie-wb-distributions/pull/486

### CODE REVIEW

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@mcimbora Out of principle this needs to be green before it's merged...

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by mcimbora** [comment]
Jenkins retest this.

**Comment by psiroky** [comment]
There were certain changes for the PR jobs, namely the ID of the check, "Jenkins CI" vs "Linux". So if the "Linux" build is green, the PR is ready to go. This is just a temporary issue for the currently opened PRs, it should not happen for newly created PRs.

**Pull request merged**
