### PR TITLE
AF-1821 - Improve health check service

### PR DESCRIPTION
**Pull request by tiagobento**
Since Uberfire's basic auth filter was removed, in order to make `/rest/ready` and `/rest/healthy` available without authentication, we have to make them be public resources.

Related PRs:
https://github.com/kiegroup/kie-wb-distributions/pull/912
https://github.com/kiegroup/kie-wb-common/pull/2583

### CODE REVIEW

**Comment by tiagobento** [comment]
Jenkins, please retest this.

**Comment by kie-ci2** [comment]
Build finished. 106 tests run, 5 skipped, 1 failed.

**Comment by tiagobento** [comment]
Jenkins, please retest this.

**Comment by tiagobento** [comment]
@domhanak Just stole your tests from https://github.com/kiegroup/kie-wb-distributions/pull/907, hope you don't mind 😝

**Comment by tiagobento** [comment]
Jenkins, please retest this.

**Comment by tiagobento** [comment]
Jenkins, please retest this.

**Comment by domhanak** [comment]
@tiagobento _What is this treachery! :D  Preferred way would be to merge my PR first, I don't like closing PR's_ :D - Anyway, not a problem at all I'll close my PR. 

Looks good, maybe you can also add test to /tests/security/ to verify that they are indeed accessible without authentication.

**Comment by tiagobento** [comment]
@domhanak Tests were added on 0220a3c to make sure these endpoints are accessible without the need for authentication. 

Is it good to merge when the build is green?

**Comment by tiagobento** [comment]
Jenkins, please retest this.

**Pull request merged**
