### PR TITLE
JBPM-8164: expose the editor as tech preview on the workbench

### PR DESCRIPTION
**Pull request by xiezhang7**
Assembly:
https://github.com/kiegroup/kie-wb-common/pull/2432
https://github.com/kiegroup/kie-wb-distributions/pull/870

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by xiezhang7** [comment]
Hi @romartin @LuboTerifaj , 

This pull request is for [JBPM-8164](https://issues.jboss.org/browse/JBPM-8164). The tech preview permission has been done in [PR#750](https://github.com/kiegroup/kie-wb-distributions/pull/750) already. I only changed the default permission value to `true` for community distribution. 

I only tested with the generated `business-central-7.17.0-SNAPSHOT-wildfly14.war`.

If `Read` is enabled for `Editors`, case modeler is enabled. (This is default settings after I launch the webapp)
screenshot from 2019-01-30 15-53-34

If `Read` is disabled for `Editors` and `Read` is enabled for `(New) Case Modeller`, case modeler is also enabled.
screenshot from 2019-01-30 15-54-00

Otherwise, case modeler is disabled.

Thanks.

**Comment by xiezhang7** [comment]
ok to test

**Comment by romartin** [comment]
Just some background: the idea is that for the community version, the new CM editor (preview) will be enabled by default, meanwhile on the productized version it'll be not. So please @LuboTerifaj , can you ensure also that it's disabled on the productized version, by default?
Thanks!

**Comment by romartin** [comment]
Jenkins retest this

**Comment by LuboTerifaj** [comment]
Hi @romartin ,

I would like to check, that Case Management (Modeller) is disabled in product build by default, but it will be possible once, there will exist one. Therefore I have opened Jira for that: https://issues.jboss.org/browse/RHPAM-1862.

Thank you!

**Comment by xiezhang7** [comment]
Hi @LuboTerifaj , 

Please find my comments below. Thanks.

> * If Editors are turned on for reading, exceptions for specific editors don't work.

I didn't change this behavior for this task. I am not sure if it is designed to work like this or it is a bug.


> * The names are different in Settings and Project perspective: _(New) Case Modeller_ vs _Case Management Preview_. Do we want to have this difference there?

I'll change the name to `Case Management (Preview) `. It is defined in the `kie-wb-common` repo.


> * This is probably not part of this Jira, but it is not possible to add exception for Case Definition. Shall I open Jira for that?

I don't really know the `Case Definition` feature. But at least, it was already there in last release. So I don't know if it is still a tech preview feature or if user should be able to enable/disable it.

**Comment by romartin** [comment]
Hey @LuboTerifaj , good job, thanks :+1: 

Also my comments below:

| If Editors are turned on for reading, exceptions for specific editors don't work.

That's probably a bug to report for the workbench administration side, not really related to this commit neither to Stunner. So feel free to create it plz :+1: 

| This is probably not part of this Jira, but it is not possible to add exception for Case Definition. Shall I open Jira for that?

Not sure if we need this but anyway feel free to open the JIRA, at least this way we'll discuss it :+1: It's not an Stunner thing again, so better report it into some other category such as `Workbench` or so.. 

Thanks!

**Comment by LuboTerifaj** [comment]
Thanks @xiezhang7 , @romartin,
reported issues:

- [JBPM-8202: Permissions exceptions for Editors don't work](https://issues.jboss.org/browse/JBPM-8202)
- [JBPM-8203: Not possible to add an Exception for Case Definition Editor](https://issues.jboss.org/browse/JBPM-8203)

**Pull request merged**
