### PR TITLE
RHBA-526: Rename Deployments to Provisioning - product version

### PR DESCRIPTION
**Pull request by jomarko**
This PR fixes inconsistency introduced by kiegroup/kie-wb-distributions#726 where the renaming was introduced just to community version of wars.

@karreiro @ryanzhang would you mind to have a look?

### CODE REVIEW

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
@karreiro @manstis @romartin please have a look on this to fix failing tests in https://github.com/kiegroup/kie-wb-common/pull/1625 (and others probably)

**Pull request merged**
