### PR TITLE
[AF-1528 ] Workbench offline

### PR DESCRIPTION
**Pull request by desmax74**
https://github.com/kiegroup/kie-wb-common/pull/2103 
https://github.com/kiegroup/appformer/pull/450
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/826
https://github.com/kiegroup/kie-soup/pull/55

@porcelli @domhanak @jhrcek

### CODE REVIEW

**Comment by porcelli** [comment]
@desmax74 you need check other places that has the `kie-wb-common-datasource-mgmt-backend` dependency (ie. https://github.com/kiegroup/kie-wb-distributions/blob/master/kie-wb-parent/kie-wb-monitoring-webapp/pom.xml) and include the dependencies there as well.

ps: you can scope those dependencies as runtime

**Comment by desmax74** [comment]
jenkins test

**Comment by desmax74** [comment]
jenkins test

**Comment by desmax74** [comment]
jenkins test

**Pull request merged**
