### PR TITLE
AF-2127: Stateless Library

### PR DESCRIPTION
**Pull request by paulovmr**
Part of an ensemble:
* https://github.com/kiegroup/kie-wb-common/pull/2808
* https://github.com/kiegroup/kie-wb-distributions/pull/954

Removed Library preferences that saved the last opened space, last opened branches and last project explorer dock state to improve performance.

### CODE REVIEW

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by ederign** [comment]
@paulovmr are the failures related? org.kie.wb.selenium.ui.StandalonePerspectivesIntegrationTest.testLibraryPerspectiveWithoutHeader

**Comment by paulovmr** [comment]
@ederign It is an unrelated and intermitent failure, the test passed in the related PR FDB https://github.com/kiegroup/kie-wb-common/pull/2808

**Pull request merged**
