### PR TITLE
added new profiles for prod and added redhat suffix

### PR DESCRIPTION
**Pull request by mbiarnes**
@psiroky tested successful on kie-releaseserver

### CODE REVIEW

**Comment by mbiarnes** [comment]
@psiroky should this be backported to 7.0.x branch?

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by psiroky** [comment]
I believe 7.0.x branch is dead, so if that is the case, we don't need to backport.

**Comment by psiroky** [comment]
Slightly different alternative with less duplication: https://github.com/kiegroup/kie-wb-distributions/pull/537

**Comment by mbiarnes** [comment]
@psiroky So we can close this PR.

**Pull request closed without merging**
