### PR TITLE
BXMSPROD-1006 GA runner hard disk clean

### PR DESCRIPTION
**Pull request by Ginxo**
**Thank you for submitting this pull request**

**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1006

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
This proposal produces up to 45G available

**Comment by Ginxo** [comment]
random failure from https://github.com/kiegroup/kie-wb-distributions/pull/1059/checks?check_run_id=1148165698 should be fixed by https://issues.redhat.com/browse/BXMSPROD-996

**Comment by Ginxo** [comment]
trying http arguments

**Comment by Ginxo** [comment]
build working https://github.com/kiegroup/kie-wb-distributions/pull/1059/checks?check_run_id=1154230758 after adding http arguments
Testing stability launching it again https://github.com/kiegroup/kie-wb-distributions/pull/1059/checks?check_run_id=1158553583

**Comment by Ginxo** [comment]
https://github.com/kiegroup/kie-wb-distributions/pull/1059/checks?check_run_id=1158553583 works again

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
