### PR TITLE
[7.67.x] JBPMN-10083 : Legacy (jBPM) Process Designer Removal - Removing Legacy Designer from kie-wb-distributions

### PR DESCRIPTION
**Pull request by inodeman**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[link](https://issues.redhat.com/browse/JBPM-10083)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

https://github.com/kiegroup/kie-wb-common/pull/3759
* link 2
* link 3 etc.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by inodeman** [comment]
Hi @romartin @LuboTerifaj can you review this cherry-pick for 7.67.x branch, War file can be found here. https://drive.google.com/drive/folders/1V3MguR74O8CHxfqWL-ZdFYXyJSzXxn2A?usp=sharing

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by inodeman** [comment]
jenkins do fdb

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by LuboTerifaj** [comment]
Hey @mareknovotny , this PR was not approved for merging. Please avoid merging PRs without reviewers approval. Thanks!

**Review by LuboTerifaj — COMMENTED** [review]
I couldn't have tested this PR since I couldn't have deployed the provided war successfully.

See my [comment](https://github.com/kiegroup/kie-wb-common/pull/3759#issuecomment-1215038308).

**Comment by mareknovotny** [comment]
have you tried the link from CI build @LuboTerifaj  ? `https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/7.67.x/job/pullrequest/job/kie-wb-distributions-7.67.x.pr/10/artifact/bc/kiegroup_kie_wb_distributions/business-central-parent/business-central-distribution-wars/business-central/target/business-central-7.67.1-SNAPSHOT-wildfly23.war`

**Comment by LuboTerifaj** [comment]
Hello @mareknovotny ,

Why that link is not linked in this PR?

I have tested it, but it works only by using jdk8. I couldn't have deployed Business Central using jdk11. However it seems the issue is not related to this PR as I couldn't have deployed it even using bcentral snapshots.

Anyway, obviously there is an issue with bcentral deployment. Do you know if it is reported?

Thanks!

**Comment by mareknovotny** [comment]
the link was not on purpose written in preformatted style ;)

What is the error? we know only about jdk8 problem with BC or more closely with jbpm-wb-showcase

**Comment by LuboTerifaj** [comment]
Hey @mareknovotny,

I meant why the CI build is not linked in the PRs automatically.

Regarding the issue I was experiencing, I've reported it here: https://issues.redhat.com/browse/RHPAM-4497

**Pull request merged**
