### PR TITLE
[7.0.x] Fix duplicate class build validation failure

### PR DESCRIPTION
**Pull request by manstis**
@mbiarnes Keep an eye on this.. when this PR is green you can try the same changes for product.

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by manstis** [comment]
Jenkins retest this please

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@mbiarnes Compiles!

Just some sporadic failing tests to contend with...

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@mbiarnes You could try this PR for product tag.. it should be OK (just trying to get damn tests to pass...)

**Comment by psiroky** [comment]
Just my $0.02: If the tests fail several times in a row, it likely means the fails are not sporadic, but rather frequent. I know no one wants to be fixing the tests, but considering how much time we spend on waiting for the tests to become green, it may just make sense to fix the tests to avoid this endless retesting :)

**Comment by manstis** [comment]
I agree.. however the tests pass locally so figuring out why they fail is
more problematic - this was meant to be a quick fix to let Michael do the
product tag build. Unfortunately the screen shots only show that login
appears incomplete.

I'll look next week after the Easter public holidays (today and Monday).

**Comment by psiroky** [comment]
@manstis I am not saying _you_ should be fixing the tests all the time. We need to share that responsibility withing the whole team (which is currently not happening).

**Comment by mbiarnes** [comment]
@manstis @psiroky so an next Tuesday, 18th of April I hope this PR will be merged

**Comment by manstis** [comment]
@mbiarnes Hi, could you please approve before I merge?

**Comment by mbiarnes** [comment]
@manstis reviewed and acked following psiroky's instructions

**Pull request merged**
