### PR TITLE
DROOLS-2863 : Unable to start standalone business central without internet access

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.jboss.org/browse/DROOLS-2863

@domhanak Hi you were marked as a tester for this.

### CODE REVIEW

**Comment by domhanak** [comment]
jenkins test this please

**Comment by domhanak** [comment]
jenkins retest this please

**Comment by domhanak** [comment]
So I tried deploying workbench from the build on wildfly11 without internet connection and it worked.

But the issues is encountered with swarm jar so I am not sure how to verify it here with upstream.
@Rikkola Any ideas? @mareknovotny Could you please comment about the swarm jar archiving, you mentioned in today's discussion?

**Comment by Rikkola** [comment]
@domhanak In either kie-wb-webapp or kie-drools-wb-webapp there is a jar file that you can use. Or you can build with productized and the jar is in the distributions-wars folders. 

To run the jar do "java -jar <name> -s <config.yml>"

And you need few configuration files to setup the users. 
[swarm-files.zip](https://github.com/kiegroup/kie-wb-distributions/files/2274186/swarm-files.zip)

**Comment by mareknovotny** [comment]
@domhanak I think @Rikkola explained that pretty detailed. We probably could add swarm jar into Jenkins job archives to not loose that for verifications. WDYT @pszubiak @mbiarnes ?

**Comment by pszubiak** [comment]
@mareknovotny @mbiarnes Yes that shouldn't be a problem.

**Comment by domhanak** [comment]
@Rikkola @mareknovotny Verified with kie-wb-webapp-swarm.jar and kie-drools-wb-webapp-swarm.jar
There is one, I think unrelated error when I run kie-wb-webapp-swarm.jar. Coud you please confirm?
I will investigate it and report if it is an issue.

`2018-08-13 11:58:37,777 ERROR [org.dashbuilder.dataset.DataSetDefRegistryImpl] (MSC service thread 1-1) Data set definition read error: jbpmExecutionErrorList.dset: java.lang.IllegalArgumentException: Provider not supported: REMOTE
        at org.dashbuilder.dataset.json.DataSetDefJSONMarshaller.readProviderType(DataSetDefJSONMarshaller.java:113)
        at org.dashbuilder.dataset.json.DataSetDefJSONMarshaller.fromJson(DataSetDefJSONMarshaller.java:85)
        at org.dashbuilder.dataset.DataSetDefRegistryCDI$2.visitFile(DataSetDefRegistryCDI.java:295)
        at org.dashbuilder.dataset.DataSetDefRegistryCDI$2.visitFile(DataSetDefRegistryCDI.java:283)
        at org.uberfire.java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:71)
        at org.uberfire.java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:96)
        at org.uberfire.java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:96)
        at org.uberfire.java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:48)
        at org.uberfire.java.nio.file.Files.walkFileTree(Files.java:1031)
        at org.uberfire.java.nio.file.Files.walkFileTree(Files.java:1052)
        at org.dashbuilder.dataset.DataSetDefRegistryCDI.listDataSetDefs(DataSetDefRegistryCDI.java:281)
        at org.dashbuilder.dataset.DataSetDefRegistryCDI.registerDataSetDefs(DataSetDefRegistryCDI.java:169)
        at org.dashbuilder.dataset.DataSetDefRegistryCDI.init(DataSetDefRegistryCDI.java:120)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:97)
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:80)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:162)
        at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
        at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
        at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
        at org.dashbuilder.dataset.DataSetDefRegistryCDI$Proxy$_$$_WeldClientProxy.registerDataSetDef(Unknown Source)
        at org.kie.workbench.common.screens.contributors.backend.dataset.ContributorsManager.init(ContributorsManager.java:115)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.invokeMethods(DefaultLifecycleCallbackInvoker.java:97)
        at org.jboss.weld.injection.producer.DefaultLifecycleCallbackInvoker.postConstruct(DefaultLifecycleCallbackInvoker.java:80)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.postConstruct(BasicInjectionTarget.java:122)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:171)
        at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
        at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
        at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:99)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
        at org.kie.workbench.common.screens.contributors.backend.dataset.ContributorsManager$Proxy$_$$_WeldClientProxy.toString(Unknown Source)
        at org.uberfire.backend.server.cdi.SystemConfigProducer.runPostConstruct(SystemConfigProducer.java:165)
        at org.uberfire.backend.server.cdi.SystemConfigProducer.afterDeploymentValidation(SystemConfigProducer.java:150)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
        at org.jboss.weld.injection.MethodInvocationStrategy$SpecialParamPlusBeanManagerStrategy.invoke(MethodInvocationStrategy.java:144)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:299)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:124)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:277)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:255)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:269)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:258)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:154)
        at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:148)
        at org.jboss.weld.bootstrap.events.AbstractContainerEvent.fire(AbstractContainerEvent.java:53)
        at org.jboss.weld.bootstrap.events.AbstractDeploymentContainerEvent.fire(AbstractDeploymentContainerEvent.java:35)
        at org.jboss.weld.bootstrap.events.AfterDeploymentValidationImpl.fire(AfterDeploymentValidationImpl.java:28)
        at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:482)
        at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:90)
        at org.jboss.as.weld.WeldStartService.start(WeldStartService.java:96)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:2032)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1955)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by Rikkola** [comment]
I don't think that is related to this issue, but a ticket is worth it to get some feedback from jbpm team.

**Comment by domhanak** [comment]
@Rikkola FYI: https://issues.jboss.org/browse/JBPM-7640

@mareknovotny this is ready for merging

**Comment by mareknovotny** [comment]
Jenkins retest this

**Pull request merged**
