### PR TITLE
Convert ProjectAuthoringPerspective to ProjectLibraryPerspective

### PR DESCRIPTION
**Pull request by tomasdavidorg**
Library perspective has higher priority so I converted ProjectAuthoringPerspective selenium test to use Library perspective only. Also it should prevent from failing builds in future.

### CODE REVIEW

**Comment by jhrcek** [comment]
+1 to merge

**Comment by psiroky** [comment]
Thanks @tomasdavidorg!

**Comment by Rikkola** [comment]
Just noticed this. Thank you @tomasdavidorg this keeps the coverage up. Our plan was to just ignore the tests we break and fix after final.

**Comment by psiroky** [comment]
@Rikkola I will pretend I have not read the part about ignoring the tests :D

**Comment by Rikkola** [comment]
Hehe. Wasn't that happy with it either. We ran all the possible scenarios and this was the result with the time we have. Ignoring or leaving Authoring in just for UI testing. Took my hat off and asked for help. Good to see we got it.

**Pull request merged**
