### PR TITLE
[7.5.x] RHBPMS-5000: Remove old jBPM-Form-Modeler

### PR DESCRIPTION
**Pull request by pefernan**
@jsoltes @mswiderski could you please review?

IMPORTANT: Don't merge untils there's a fix for this JBPM-6499 on jbpm-designer (https://github.com/kiegroup/jbpm-designer/pull/681)

This PR is a part of an ensemble:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/580
https://github.com/kiegroup/kie-wb-common/pull/1241
https://github.com/kiegroup/jbpm-wb/pull/919
https://github.com/kiegroup/kie-wb-distributions/pull/641
https://github.com/kiegroup/kie-wb-playground/pull/41

### CODE REVIEW

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins execute full downstream build

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins retest this

**Comment by pefernan** [comment]
jenkins please retest this

**Comment by pefernan** [comment]
jenkins please retest this

**Comment by pefernan** [comment]
jenkins please retest this

**Comment by psiroky** [comment]
@pefernan blindly re-testing won't help. There was another issue which I just fixed. Once the jenkins is restarted again, the build should then work.

**Comment by pefernan** [comment]
@psiroky sorry I'm kind of desperate now....

**Pull request merged**
