### PR TITLE
RHPAM-4455 org.w3c:dom dependency to business-central

### PR DESCRIPTION
**Pull request by Ginxo**
the `org.w3c.dom.ElementTraversal` class is not present for jdk8, so we force org.w3c:dom dependency to be present.
As soon as we agree this is the right proposal, I will propagate it to `7.67.x` and `7.67.x-blue` branches
Built and tested either with JDK11 and 8.

**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4455

**referenced Pull Requests**: 

* https://github.com/kiegroup/kie-wb-distributions/pull/1173
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023
* https://github.com/kiegroup/kie-wb-common/pull/3755
* https://github.com/kiegroup/droolsjbpm-integration/pull/2835

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by Ginxo** [comment]
Jenkins run fdb

**Comment by Ginxo** [comment]
This is locally working running the same command as CI is doing for 
```
build-chain-action -folder pr_build -df 'https://raw.githubusercontent.com/${GROUP:kiegroup}/droolsjbpm-build-bootstrap/${BRANCH:main}/.ci/pull-request-config.yaml' build pr -url https://github.com/kiegroup/kie-wb-distributions/pull/1173
```

Java Version
```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment 18.9 (build 11.0.12+7)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode)
```

Maven Version
```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: X
Java version: 11.0.12, vendor: Oracle Corporation, runtime: X/java/11.0.12-open
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.17.5-300.fc36.x86_64", arch: "amd64", family: "unix"
```
Still investigating

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
So i changed to JDK 11.0.16 and maven 3.8.1 and it's failing locally. Testing just JDK 11.0.16 just to confirm it is not maven version

**Comment by tomasdavidorg** [comment]
Hi @Ginxo, I am able to start the jbpm-server-dist with JDK 8 but not with the JDK 11. In both I can see some errai errors like these:
```
2022-08-08 13:27:27,784 ERROR [stderr] (MSC service thread 1-2) ----------
2022-08-08 13:27:27,785 ERROR [stderr] (MSC service thread 1-2) 1. ERROR in /tmp/tdavid/errai/54885013d5cabb07713c884a93d8133e1f67e/errai.gen/classes/org/jboss/errai/cdi/EventQualifierSerializerImpl.java (at line 4)
2022-08-08 13:27:27,785 ERROR [stderr] (MSC service thread 1-2) 	import javax.inject.Named;
2022-08-08 13:27:27,786 ERROR [stderr] (MSC service thread 1-2) 	       ^^^^^^^^^^^^
2022-08-08 13:27:27,786 ERROR [stderr] (MSC service thread 1-2) The import javax.inject cannot be resolved
2022-08-08 13:27:27,786 ERROR [stderr] (MSC service thread 1-2) ----------
2022-08-08 13:27:27,787 ERROR [stderr] (MSC service thread 1-2) 2. ERROR in /tmp/tdavid/errai/54885013d5cabb07713c884a93d8133e1f67e/errai.gen/classes/org/jboss/errai/cdi/EventQualifierSerializerImpl.java (at line 5)
2022-08-08 13:27:27,788 ERROR [stderr] (MSC service thread 1-2) 	import org.jboss.errai.common.client.util.AnnotationPropertyAccessorBuilder;
2022-08-08 13:27:27,788 ERROR [stderr] (MSC service thread 1-2) 	       ^^^^^^^^^^^^^^^^^^^^^^
2022-08-08 13:27:27,789 ERROR [stderr] (MSC service thread 1-2) The import org.jboss.errai.common cannot be resolved
2022-08-08 13:27:27,789 ERROR [stderr] (MSC service thread 1-2) ----------
2022-08-08 13:27:27,790 ERROR [stderr] (MSC service thread 1-2) 3. ERROR in /tmp/tdavid/errai/54885013d5cabb07713c884a93d8133e1f67e/errai.gen/classes/org/jboss/errai/cdi/EventQualifierSerializerImpl.java (at line 6)
2022-08-08 13:27:27,791 ERROR [stderr] (MSC service thread 1-2) 	import org.jboss.errai.common.client.util.SharedAnnotationSerializer;
2022-08-08 13:27:27,791 ERROR [stderr] (MSC service thread 1-2) 	       ^^^^^^^^^^^^^^^^^^^^^^
2022-08-08 13:27:27,792 ERROR [stderr] (MSC service thread 1-2) The import org.jboss.errai.common cannot be resolved
```

with the JDK 11 there is also error like this:
```
2022-08-08 13:15:50,640 ERROR [org.jboss.errai.reflections.Reflections] (Thread-92) could not create Vfs.Dir from url. ignoring the exception and continuing: org.jboss.errai.reflections.ReflectionsException: could not create Dir using org.jboss.errai.common.metadata.JbossVFsTypeHandler from url vfs:/content/jbpm-casemgmt.war/WEB-INF/lib/uberfire-backend-api-7.74.0-SNAPSHOT.jar/
	at deployment.jbpm-casemgmt.war//org.jboss.errai.reflections.vfs.Vfs.fromURL(Vfs.java:137)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.reflections.vfs.Vfs.fromURL(Vfs.java:124)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.reflections.Reflections.scan(Reflections.java:245)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.common.metadata.MetaDataScanner.<init>(MetaDataScanner.java:120)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.common.metadata.MetaDataScanner.createInstance(MetaDataScanner.java:97)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.common.metadata.MetaDataScanner.createInstance(MetaDataScanner.java:84)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.common.metadata.MetaDataScanner.createInstance(MetaDataScanner.java:80)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.common.metadata.ScannerSingleton.lambda$static$0(ScannerSingleton.java:49)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: java.nio.file.NoSuchFileException: /content
	at deployment.jbpm-casemgmt.war//org.jboss.errai.reflections.vfs.ZipDir.<init>(ZipDir.java:43)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.reflections.vfs.ZipDir.<init>(ZipDir.java:33)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.common.metadata.JbossVFsTypeHandler.createDir(JbossVFsTypeHandler.java:94)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.reflections.vfs.Vfs.fromURL(Vfs.java:134)
	... 9 more
Caused by: java.nio.file.NoSuchFileException: /content
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1259)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
	at deployment.jbpm-casemgmt.war//org.jboss.errai.reflections.vfs.ZipDir.<init>(ZipDir.java:42)
	... 12 more
```

Server logs are here:
[jdk8-server.log](https://github.com/kiegroup/kie-wb-distributions/files/9281440/jdk8-server.log)
[jdk11-server.log](https://github.com/kiegroup/kie-wb-distributions/files/9281444/jdk11-server.log)

**Comment by Ginxo** [comment]
@tomasdavidorg I'm still investigating it. The build is failing for Java 11.0.16 specifically (but for <11.0.16), I'm still trying to figure out what's causing the error.

**Comment by Ginxo** [comment]
whole RHBA stream taken from before `2022-07-22T09:48:00` and still failing with Java 11.0.16

**Comment by Ginxo** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by Ginxo** [comment]
@mareknovotny I'm testing 11.0.2 version by https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-wb-distributions-main.pr/169 I will let you know as soon as we have any output

**Comment by Ginxo** [comment]
> @mareknovotny I'm testing 11.0.2 version by https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-wb-distributions-main.pr/169 I will let you know as soon as we have any output

it is already working for 11.0.2, see https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-wb-distributions-main.pr/169

**Comment by mareknovotny** [comment]
have you switched the builder to java 11.0.2 then? just to see it here for all other PRs? @Ginxo

**Comment by Ginxo** [comment]
tested and working for:
* 11.0.15 https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-wb-distributions-main.pr/185
* 11.0.2 https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-wb-distributions-main.pr/186

**Pull request merged**
