### PR TITLE
KIECLOUD-256: Default to ocp/k8s backed uberfire java nio2 file system implementation 

### PR DESCRIPTION
**Pull request by rhtevan**
For Business Central Monitoring cloud image distribution

Signed-off-by: Evan Zhang <evan.zhang@redhat.com>

Prerequisite PRs:
https://github.com/kiegroup/appformer/pull/799
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1152

### CODE REVIEW

**Comment by rhtevan** [comment]
@porcelli @sutaakar The prerequisite PR got merged. Not sure who can help merge this one. Thanks.

**Comment by porcelli** [comment]
please assignees take a look on this, if all good please approve and lets get it merged

**Comment by rhtevan** [comment]
@ederign Eder, is this something you could take a quick look and help it get merged? Thanks!

**Comment by paulovmr** [comment]
jenkins retest this

**Comment by rhtevan** [comment]
@sutaakar Looks like the failure from the integration test caused by missing classes. Don't recall we need to explicitly specify the new module. Any clue?

`
[31m12:41:46,004 ERROR [org.uberfire.java.nio.file.api.FileSystemProviders] (MSC service thread 1-8) Can't initialize FileSystemProviders: java.util.ServiceConfigurationError: org.uberfire.java.nio.file.spi.FileSystemProvider: Provider org.uberfire.java.nio.fs.k8s.K8SFileSystemProvider not found
`

**Comment by ederign** [comment]
Hi @rhtevan, I can merge this as soon as the unit tests are fixed. If necessary ping me on gchat!

**Comment by sutaakar** [comment]
@rhtevan It seems that all providers have to be on classpath as the appformer code iterates through all available providers - https://github.com/kiegroup/appformer/blob/master/uberfire-nio2-backport/uberfire-nio2-api/src/main/java/org/uberfire/java/nio/file/api/FileSystemProviders.java#L70

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by rhtevan** [comment]
@sutaakar Fixing this packaging issue by adding explicit dependency to monitoring-webapp pom which requires any PR to [bootstrap](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1152). 
could take a quick look and trigger a retest. Thanks.

**Comment by sutaakar** [comment]
Jenkins retest this

**Comment by rhtevan** [comment]
@ederign Issue being fixed, could you help merge it along side with this dependent PR (kiegroup/droolsjbpm-build-bootstrap#1152). Full green now, thanks @sutaakar !

**Pull request merged**
