### PR TITLE
Update selenium tests after the merge of project oriented

### PR DESCRIPTION
**Pull request by jhrcek**
@paulovmr ProjectLibraryIntegrationTest is failing now on master after project oriented has been merged. The root cause is the change in behaviour in Project Import screen:
- previously after selecting projects in import screen and clicking OK the app automatically moved to Project List.
- current behaviour (seems broken): after clicking OK, the app stays in the list of projects to import. Is this reported/should I report it?

Also fixed the issue with screenshot on failure showing login screen (we must not put logout into `@After` methods) and did a general code cleanup in selenium module.

@manstis @karreiro FYI this is the fix of selenium tests as promised yesterday. Let me retest this few times to confirm stability..

### CODE REVIEW

**Comment by manstis** [comment]
@jhrcek @paulovmr @adrielparedes was looking into the reported problem relating to importing examples.

See https://issues.jboss.org/browse/DROOLS-2310

**Comment by jhrcek** [comment]
Great, In that case I'll remove the [workaround](https://github.com/kiegroup/kie-wb-distributions/pull/687/files#diff-6da83ab05d0c02c0260b3f7c7afe0349R77) after that issue is fixed. @adrielparedes should we wait for the fix before merging this, or are you going to work on that later?

**Comment by adrielparedes** [comment]
@jhrcek I'm working on this right now, so If you give me some time today I will upload the fix. I already talked with @paulovmr to see where could the problem be located.

**Comment by jhrcek** [comment]
Good @adrielparedes no pressure, this can be merged next week ;)

**Comment by jhrcek** [comment]
jenkins retest this to confirm that selenium tests are stable..

**Comment by adrielparedes** [comment]
@jhrcek here is the issue you are expecting to be merged first: https://github.com/kiegroup/kie-wb-common/pull/1421

**Comment by jhrcek** [comment]
Removed workaround for issue addressed in https://github.com/kiegroup/kie-wb-common/pull/1421 
The tests are expected to fail now and shoud be fixed once that PR is merged.

**Comment by jhrcek** [comment]
jenkins retest this

**Comment by jhrcek** [comment]
Last try to confirm stability jenkins retest this

**Comment by jhrcek** [comment]
@manstis ready to merge. Please squash when merging.

**Pull request merged**
