### PR TITLE
DROOLS-2566: [DMN Editor] Integrate Editor into Workbench

### PR DESCRIPTION
**Pull request by manstis**
See https://issues.jboss.org/browse/DROOLS-2566

This also incorporates https://issues.jboss.org/browse/DROOLS-2748

### CODE REVIEW

**Comment by manstis** [comment]
Part of an ensemble:

- https://github.com/kiegroup/kie-wb-common/pull/1988
- https://github.com/kiegroup/kie-wb-distributions/pull/781

**Comment by manstis** [comment]
```
[INFO]    Compiling 2 permutations
[INFO]       Compiling permutation 0...
[INFO]       [ERROR] OutOfMemoryError: Increase heap size or lower gwt.jjs.maxThreads
[INFO] java.lang.OutOfMemoryError: Java heap space
```

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
```
[INFO]    Compiling 2 permutations
[INFO]       Compiling permutation 0...
[INFO]       [ERROR] OutOfMemoryError: Increase heap size or lower gwt.jjs.maxThreads
[INFO] java.lang.OutOfMemoryError: Java heap space
```

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@jomarko @karreiro Could you please endeavour to review today?

@etirelli has requested this integration be in 7.9.0.Final.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@mbiarnes Hi.... so we spoke earlier today about this PR :-(

It keeps failing due to OOM.. I see the Jenkins job is configured ```Xmx2G``` can we try increasing it? I also see the job's description says not to modify it manually - so I have not! Would you be able to try increasing this?

**Comment by manstis** [comment]
@etirelli FYI.. the failing job for DMN integration.. When this goes green we're all happy :-)

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by karreiro** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by mbiarnes** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@mbiarnes Failed. OOM. Can we try the ```MAVEN_OPTS``` 3G too please (to be sure we've tried everything).

**Comment by kiereleaseuser** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by manstis** [comment]
Jenkins please execute full downstream build.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by manstis** [comment]
@mbiarnes @pszubiak Is it worth starting this again? Do you have anything new to try?

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@mbiarnes Build succeeded (well.. GWT was all OK.. just a couple of _flaky_ tests).

Jenkins please rebuild this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@jomarko @karreiro The GWT compilation issue (heap space) has been fixed by @mbiarnes. All that remains (for the last three builds) is a varying number of failing REST tests. These are possibly known issues (and possibly fixed by https://github.com/kiegroup/kie-wb-distributions/pull/778 and/or https://github.com/kiegroup/kie-wb-distributions/pull/782). More recently there appears to be some failing Selenium tests; but those too appear unrelated (the DMN Editor is not enabled).

WDYT about merging this (and its related PR) sooner than later?

**Comment by karreiro** [comment]
@manstis +1 for merging them.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
@Rikkola @jhrcek This PR keeps failing due to varying REST Unit Test [failures](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-distributions-pullrequests/1405/). I see you have a couple of PRs fixing a similar (identical?) issue. In your opinion are the failures on this PR something we can ignore for now (i.e. merge this "as is")?

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
@manstis I see the priority of this PR. however I think if we decide merge without green tests we just move the same problem one PR later. We should help @jhrcek with stabilization of those unstable tests I think.

**Comment by Rikkola** [comment]
I think my PR gets being hit by the issue @jhrcek's issue fixes and he might be getting hit by mine. Argh!

**Comment by Rikkola** [comment]
Ok. The problem is the REST bit that selenium uses to clean up. There is a weird random long delay when all the projects are removed. I have feeling these take a while to fix. Should we disable Selenium and REST tests while we fix this or not?

**Comment by jomarko** [comment]
@Rikkola From my point of view, add **@Ignore** to given flaky tests is totally fine, but please keep in mind we have to file a jira to fix the given tests, assign to proper people and plan it actively to our sprints, however you were on @jhrcek talk on F2F so probably you know this.

**Comment by Rikkola** [comment]
@jomarko Yes, I was just thinking if we are now in that situation where we use Ignore and do the fix on side.

**Comment by Rikkola** [comment]
I was waiting for @jhrcek's comment, but looks like is is on PTO for few days.
@manstis If you have story points for the task that would be great. I can also do it, but on the middle of something right now. I can do it tomorrow morning.

**Comment by manstis** [comment]
@Rikkola @jomarko @jhrcek Please see https://github.com/kiegroup/kie-wb-distributions/pull/786

**Comment by jomarko** [comment]
Yes, @jhrcek is on PTO. He will be back on Wednesday.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by manstis** [comment]
Jenkins please retest this.

**Comment by jomarko** [comment]
Retested 28 times, I think ready for merge :)

**Pull request merged**
