### PR TITLE
Replace swarm-plugin with cargo-plugin in Kie-wb-tests

### PR DESCRIPTION
**Pull request by jakubschwan**
Replace swarm plugin with cargo plugin in Kie-wb-tests to have unificated configuration of containers.
Also there was test configuration issue on swarm - tests couldn't be executed on swarm.

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins retest please

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by mareknovotny** [comment]
Jenkins retest please

**Comment by mareknovotny** [comment]
@jakubschwan i got the error here

```
Unexpected error while executing the Upstream repositories builder for PR builds! null
java.lang.NullPointerException
```
there is a bug in PR builder, please close this and resend as the new PR

**Comment by jakubschwan** [comment]
@mareknovotny @cristianonicolai new PR created - see #749

**Pull request closed without merging**
