### PR TITLE
JBPM-8345: fix disabling case modeller in security policy

### PR DESCRIPTION
**Pull request by xiezhang7**

### CODE REVIEW

**Comment by xiezhang7** [comment]
Hi @romartin @LuboTerifaj , created pull request for master branch. Thanks.

**Comment by xiezhang7** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@xiezhang7 you should duplicate the RHPAM ticket into a JBPM one please, in order to merge into master. We need this for ticket tracking purposes... thanks! Also update the commit's name to reflect JBPM ticket, instead of RHPAM one.

**Comment by xiezhang7** [comment]
> @xiezhang7 you should duplicate the RHPAM ticket into a JBPM one please, in order to merge into master. We need this for ticket tracking purposes... thanks! Also update the commit's name to reflect JBPM ticket, instead of RHPAM one.

Hi @romartin , I have created a new ticket [JBPM-8345](https://issues.jboss.org/browse/JBPM-8345). Thanks.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hello @xiezhang7 , @romartin 

I am not sure how to test it since I don't have productized build. I can only check that upstream version is not broken. Or can I do it in any different way?

Is it possible to generate full downstream build here? I am asking because my comment above didn't trigger Jenkins build.

Thank you!

**Comment by romartin** [comment]
Jenkins execute full downstream build

**Comment by romartin** [comment]
@LuboTerifaj it should work... just re-fired the build again, let's see

**Comment by xiezhang7** [comment]
Hi @LuboTerifaj , 

You can take the business central war file, edit the /WEB-INF/classes/security-policy.properties file. In the file change value of property `default.permission.editor.read.CaseManagementEditor` to `false`. And then case modeler should be disabled in business central by default.

Value of this property is set to `false` in the security-policy.properties file for product build. And we are sure the correct property file is used for product build, because all other properties work properly in the product build. 

So I think it is good enough to test with the community build by changing the property value.

Thanks.

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Comment by LuboTerifaj** [comment]
Hey @romartin , it seems that full downstream build doesn't work here. Do you have any idea why it doesn't work?

**Comment by LuboTerifaj** [comment]
Jenkins execute full downstream build

**Pull request merged**
