### PR TITLE
RHBPMS-5198 Duplicate class name, business central persistence.xml fi…

### PR DESCRIPTION
**Pull request by bxf12315**
…le (BPMS 6.4)
@cristianonicolai  Is it right? Please review it.

### CODE REVIEW

**Comment by mareknovotny** [comment]
@bxf12315  yes, this is really minor issue not requested for now, we can add it, but there are still more important issue you should backport

**Comment by mareknovotny** [comment]
Jenkins retest this

**Comment by bxf12315** [comment]
@mareknovotny Thank you

**Comment by mareknovotny** [comment]
Jenkins retest this

**Pull request closed without merging**
