### PR TITLE
update to WildFly23

### PR DESCRIPTION
**Pull request by mbiarnes**
**Thank you for submitting this pull request**

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1626
https://github.com/kiegroup/jbpm/pull/1917
https://github.com/kiegroup/appformer/pull/1134
https://github.com/kiegroup/droolsjbpm-integration/pull/2460
https://github.com/kiegroup/jbpm-wb/pull/1489
https://github.com/kiegroup/kie-wb-distributions/pull/1098

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by Ginxo** [comment]
@mbiarnes can you please rebase master
This https://github.com/kiegroup/kie-wb-distributions/pull/1101 (already merged) fixes the GA error. Thanks.

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
This PR will be closed since Tiago Bento and William Siqueira are working on the same issue:
https://github.com/kiegroup/kie-wb-distributions/pull/1115

**Pull request closed without merging**
