### PR TITLE
Replace swarm-plugin with cargo-plugin in Kie-wb-tests

### PR DESCRIPTION
**Pull request by jakubschwan**
Replace swarm plugin with cargo plugin in Kie-wb-tests to have unificated configuration of containers.
Also there was test configuration issue on swarm - tests couldn't be executed on swarm.

New PR instead of #741

### CODE REVIEW

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by jakubschwan** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by jakubschwan** [comment]
I'll open a new PR from different branch to avoid a NPE in PR Build.

**Pull request closed without merging**
