### PR TITLE
JBPM-7372 - single zip distribution for jBPM

### PR DESCRIPTION
**Pull request by mswiderski**
@krisv @tsurdilo @mbiarnes actual distribution content

depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/767

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski thanks!

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
@tsurdilo @mswiderski @krisv I did the test with both PR (one droolsjbpm-build-boostrap and kie-wb-distributions) and it worked properly. No test failures.

**Comment by mareknovotny** [comment]
how is it supposed to work with productized profile where is build only eap7 type of deployment not wildfly11?
I think if there is not inclusion in the product, we need to change a little the upstream deployment GAVs to be in special profile.
WDYT?

**Comment by mbiarnes** [comment]
+1

**Pull request merged**
