### PR TITLE
[RHPAM-4656] update EAP XP to version 4.0.0.GA-redhat-00017

### PR DESCRIPTION
**Pull request by rgdoliveira**
This prod version is EAP XP on top of EAP 7.4.10

**JIRA**: https://issues.redhat.com/browse/RHPAM-4656

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Review by mareknovotny — APPROVED** [review]

**Comment by mareknovotny** [comment]
failed tests in Product FDB (they seems not related):

- com.redhat.installer.tests.asconfiguration.jdbc.validator.JDBCConnectionUtilsTest.testVerifyJarPathInvalid

- com.redhat.installer.tests.asconfiguration.keystore.validator.JSSEValidatorTest.testWrongTruststoreTypeSpecified
- com.redhat.installer.tests.asconfiguration.keystore.validator.JSSEValidatorTest.testWrongKeystoreTypeSpecified
- com.redhat.installer.tests.ports.validator.PortCollisionValidatorTest.testDomainHaExcludes
- com.redhat.installer.tests.ports.validator.PortCollisionValidatorTest.testStandaloneFullHaExcludes
- com.redhat.installer.tests.ports.validator.PortCollisionValidatorTest.testStandaloneHaExcludes
-

**Review by lampajr — APPROVED** [review]

**Review by tomasdavidorg — APPROVED** [review]
Looks good to me. I am just thinking where those tests come from. Seeing these tests/issues for the first time.

**Comment by mareknovotny** [comment]
these tests are only in Product FDB - in Installer and i noticed/check them they are failing also in droolsjbpm-build-bootstrap product FDB, so something broken in the testsuite or so.
fyi @rgdoliveira @lampajr

**Comment by rgdoliveira** [comment]
@mareknovotny @lampajr yeah, those tests that are failing are part of `jboss-integration/installer-commons` project and it only fails when running Product FDB because only in this profile that the installer projects are built. So it is not related to the EAP XP4 upgrade.

I can take a look at those test failures and try to understand why they are failing.

**Pull request merged**
