### PR TITLE
JBPM-7250: Home page blank for users with manager, user and process-a…

### PR DESCRIPTION
**Pull request by nmirasch**
…dmin role

### CODE REVIEW

**Comment by nmirasch** [comment]
@cristianonicolai could you take a look? Thanks

**Comment by cristianonicolai** [comment]
@jhrcek +1 these tests are relevant to the changes applied in here, we should update it accordingly.

**Comment by nmirasch** [comment]
@jhrcek @cristianonicolai thanks, I missed them. Added now the changes to that tests

**Comment by jhrcek** [comment]
@nmirasch Thanks for the tests. There's just one thing that confuses me now:
The original issue is about missing home access for process-admin,manager and user. But I see this PR adds access only to process-admin and manager - isn't user missing?

**Comment by nmirasch** [comment]
@jhrcek yes, it was added in  https://github.com/kiegroup/kie-wb-distributions/pull/744 but not the tests related. I have included the user role one in this PR.

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Comment by cristianonicolai** [comment]
jenkins please retest this

**Pull request merged**
