### PR TITLE
JBPM-7902 - Use auth configuration to avoid invalidating session

### PR DESCRIPTION
**Pull request by cristianonicolai**

### CODE REVIEW

**Comment by nmirasch** [comment]
Jenkins retest this please

**Comment by nmirasch** [comment]
Jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@cristianonicolai @ederign @nmirasch  build was UNSTABLE - test failed but the build ws successful.
Should the be merged then?

**Comment by cristianonicolai** [comment]
@mbiarnes all good to merge now.

**Pull request merged**
