### PR TITLE
JBPM-9959 business-central/docs/ do not required to login

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: 

https://issues.redhat.com/browse/JBPM-9959

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins run fdb

**Review by cristianonicolai — APPROVED** [review]

**Review by cristianonicolai — APPROVED** [review]

**Comment by barboras7** [comment]
Thank you for the PR Xiaofeng. I checked the business central from the FDB and the login seems to be required also for docs/ now. I have one question. The login page is not correctly displayed, see the attached image. Any idea why this is happening? 
Screenshot from 2021-11-26 10-49-28
The login page should look like this 
Screenshot from 2021-11-26 10-49-35

**Comment by bxf12315** [comment]
> Thank you for the PR Xiaofeng. I checked the business central from the FDB and the login seems to be required also for docs/ now. I have one question. The login page is not correctly displayed, see the attached image. Any idea why this is happening? Screenshot from 2021-11-26 10-49-28 The login page should look like this Screenshot from 2021-11-26 10-49-35

I can not reproduce it.

**Comment by barboras7** [comment]
https://user-images.githubusercontent.com/11525583/143605874-ee5edf6e-c2d4-430f-a4b9-fd934ecebf3f.mp4

**Comment by bxf12315** [comment]
> Screencast.from.11-26-2021.03.49.40.PM.mp4

https://user-images.githubusercontent.com/209745/143685114-cdd5aaa3-cc2e-4f59-81ef-ba033b09f7be.mov

**Comment by barboras7** [comment]
Hi @bxf12315,
I have tried both Firefox and Chrome, both with cleared caches. Also, another colleague tried it and the same thing was happening in his environment. Could you please try to clear your cache or use different browser?

**Comment by barboras7** [comment]
The issue discussed above is not caused by this PR and does affect also some other URLs (for example http://localhost:8080/business-central/plugins/). This PR can be merged and a separate Jira was created for the discussed issue.

**Review by barboras7 — APPROVED** [review]

**Pull request merged**
