### PR TITLE
RHPAM-2532: Remove git daemon workaround and fix RepositoryIntegratio…

### PR DESCRIPTION
**Pull request by jakubschwan**
…nTest

Signed-off-by: Jakub Schwan <jschwan@redhat.com>

Reopened PR #991 so GHPR plugin can properly use branches

### CODE REVIEW

**Comment by jakubschwan** [comment]
jenkins execute full downstream build

**Comment by mareknovotny** [comment]
FDB for leaf repo like kie-wb-distributions doesn't make sense ;) just repository PR CI job is enough. Nothing happens just for next time reminder.

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by domhanak** [comment]
Jenkins retest this please

**Pull request merged**
