### PR TITLE
BXMSPROD-33 add wildfly zip assembly and remove the assembly-kie-wb-eap-7.xml file and its references

### PR DESCRIPTION
**Pull request by Ginxo**

### CODE REVIEW

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by mareknovotny** [comment]
@domhanak can you review now the change?

**Comment by domhanak** [comment]
@mareknovotny yes, I will get to it after CR1

**Comment by jomarko** [comment]
@mareknovotny Hi, I think we should do this "cleanup" also on `business-central-tests/pom.xml`, what do you think? There seems to be a lot of properties to enable testing on eap7.

**Pull request merged**
