### PR TITLE
AF-1424: Support SSH keystore with workbench

### PR DESCRIPTION
**Pull request by pefernan**
AF-1275: SSH Keystore backend
AF-1274: SSH Keystore UI
AF-1277: Integrate SSH Keystore with VFS SSH

@ederign @domhanak could you please take a look?

This is part of an ensemble, please merge with:
https://github.com/kiegroup/appformer/pull/492
https://github.com/kiegroup/kie-wb-common/pull/2177
https://github.com/kiegroup/kie-wb-distributions/pull/829
https://github.com/kiegroup/drools-wb/pull/959
https://github.com/kiegroup/jbpm-wb/pull/1215
https://github.com/kiegroup/optaplanner-wb/pull/308
https://github.com/kiegroup/kie-docs/pull/1156

### CODE REVIEW

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by domhanak** [comment]
jenkins retest this

**Comment by domhanak** [comment]
Roses are red,
violets are blue,
Jenkins execute full downstream build!

**Comment by pefernan** [comment]
Jenkins execute full downstream build

**Comment by ederign** [comment]
@pefernan could you please fix the conflicts ?

**Comment by ederign** [comment]
jenkins retest this

**Pull request merged**
