### PR TITLE
RHPAM-2748 :Update locale selection drop down to include only the supported languages for RHDM and RHPAM

### PR DESCRIPTION
**Pull request by RishiRajAnand**
- Commented the code that includes non-translated locales
- language dropdown to show only supported locales (English, Japanese,Spanish, French )

Part of an ensemble:
- https://github.com/kiegroup/kie-wb-common/pull/3191
- https://github.com/kiegroup/kie-wb-distributions/pull/1018

### CODE REVIEW

**Comment by manstis** [comment]
@jomarko IDK if you have any interest in this (or know of a better QE representative to look)?

**Comment by jomarko** [comment]
@manstis I asked Barbora for review, to align with Jira. Thank you.

**Comment by RishiRajAnand** [comment]
@manstis I have removed the lines. As discussed with @mbiarnes , we are can just disable the locales and later he can remove the .properties file

**Comment by RishiRajAnand** [comment]
Jenkins retest this please

**Comment by dgutierr** [comment]
@RishiRajAnand what about removing locales from https://github.com/kiegroup/kie-wb-distributions/blob/master/business-central-parent/business-monitoring-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml ?

**Comment by RishiRajAnand** [comment]
@dgutierr Changes done, Thanks for observation.

**Pull request merged**
