### PR TITLE
RHPAM-4431: Session Cookie Without Secure Attribute Set

### PR DESCRIPTION
**Pull request by RishiRajAnand**
**Thank you for submitting this pull request**

**RHPAM-4431**: https://issues.redhat.com/browse/RHPAM-4431

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Review by tomasdavidorg — APPROVED** [review]

**Comment by RishiRajAnand** [comment]
Jenkins retest this

**Comment by RishiRajAnand** [comment]
Jenkins retest this

**Comment by RishiRajAnand** [comment]
Jenkins retest this

**Comment by RishiRajAnand** [comment]
Jenkins run cdb

**Comment by RishiRajAnand** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
isn't needed to change also selenium tests which are failing? @tomasdavidorg

**Comment by tomasdavidorg** [comment]
@mareknovotny I ran the tests locally and they passed. Not sure what is the problem. Looking at the log and screenshots and it seems that nothing appeared on the screen. I will try to investigate it more.

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by tomasdavidorg** [comment]
Snímek obrazovky 2023-04-06 v 10 04 38

**Comment by mareknovotny** [comment]
fyi @mbiarnes could you please create jira task and update Firefox to the latest ESR?

**Comment by Ginxo** [comment]
@tomasdavidorg `firefox-91esr` is already available on the machine, trying with this one before going to something higher like `111.0`

**Comment by Ginxo** [comment]
* this PR with `firefox-esr91` https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-wb-distributions-main.pr/226/

**Comment by Ginxo** [comment]
@tomasdavidorg @mareknovotny according to https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/main/job/pullrequest/job/kie-wb-distributions-main.pr/226/ :green_circle: 
as soon as we merge https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2253 this PR checks should be green

**Comment by mareknovotny** [comment]
/
jenkins retest this please

**Pull request merged**
